export default {
    "1 & 1 Ionos": "Telecommunication",
    "ABOUT YOU GmbH": "Retail & Consumption",
    "Acronis Germany GmbH": "IT",
    "Ada Health GmbH": "Health & Social",
    "AdColony GmbH": "Internet & Multimedia",
    "Adform Germany GmbH": "Internet & Multimedia",
    "Adidas AG": "Textile & Fashion",
    "Allianz SE": "Insurance",
    "Amazon Europe Core SARL": "Retail & Consumption",
    "APPLE INC.": "IT",
    "ASOS Germany GmbH": "Internet & Multimedia",
    "Auto 1 Group GmbH": "Internet & Multimedia",
    "auxmoney GmbH": "Banks & Finance",
    "Baker & McKenzie International B.V.": "Law & Taxes",
    "BASF SE": "Chemical & Pharmazeutical",
    "Bayer AG": "Chemical & Pharmazeutical",
    "Blacklane GmbH": "Traffic & Transport & Logistics",
    "Bayerische Motoren Werke AG": "Automotive",
    "BOOHOO GROUP PLC": "Retail & Consumption",
    "booking.com B.V.": "Internet & Multimedia",
    "Check24 Vergleichsportal GmbH": "Internet & Multimedia",
    "CLOUD & HEAT Technologies GmbH": "IT",
    "Comuto Deutschland GmbH": "Traffic & Transport & Logistics",
    "Contentful GmbH": "Culture & Entertainment & Events",
    "DB Vertrieb GmbH": "Traffic & Transport & Logistics",
    "Deliveroo Germany gmbH": "Retail & Consumption",
    "Delivery Hero SE": "Retail & Consumption",
    "Deposit Solutions GmbH": "Banks & Finance",
    "Doctolib GmbH": "Health & Social",
    "Dreamlines Tours GmbH": "Traffic & Transport & Logistics",
    "eGym GmbH": "Health & Social",
    "FC Bayern München AG": "Culture & Entertainment & Events",
    "FinanceFox Beteiligung GmbH": "Banks & Finance",
    "FlixMobility GmbH": "Traffic & Transport & Logistics",
    "GetYourGuide Deutschland GmbH": "Service",
    "GOEURO Travel GmbH": "Traffic & Transport & Logistics",
    "Google LLC": "Internet & Multimedia",
    "Gruner + Jahr GmbH": "Culture & Entertainment & Events",
    "Hellofresh SE": "Retail & Consumption",
    "Helpling GmbH & Co. KG": "Service",
    "Inter IKEA Systems B.V.": "Retail & Consumption",
    "Immobilien Scout GmbH": "Real Estate & Facility Management",
    "Intel Deutschland GmbH": "IT",
    "Jobandtalent DE GmbH": "Service",
    "Klarna GmbH": "Banks & Finance",
    "Kreditech Holding SSL GmbH": "Banks & Finance",
    "Launchmetrics Germany GmbH": "Internet & Multimedia",
    "yd. yourdelivery GmbH": "Retail & Consumption",
    "MAINSTAY MEDICAL INTERNATIONAL PUBLIC LIMITED COMPANY": "Health & Social",
    "MessageBird GmbH": "Internet & Multimedia",
    "mobile.de GmbH": "Retail & Consumption",
    "N26 Bank GmbH": "Banks & Finance",
    "Nestle S.A.": "Retail & Consumption",
    "Netflix International B.V.": "Culture & Entertainment & Events",
    "Otto (GmbH & Co KG)": "Retail & Consumption",
    "Outfittery GmbH": "Retail & Consumption",
    "Pro Sieben Sat.1 Media": "Culture & Entertainment & Events",
    "Raisin GmbH": "Banks & Finance",
    "ResearchGate GmbH": "Internet & Multimedia",
    "Roche Deutschland Holding GmbH": "Chemical & Pharmazeutical",
    "Rocket Internet SE": "Internet & Multimedia",
    "Samsung Electronics GmbH": "Internet & Multimedia",
    "SAP Deutschland SE & Co. KG": "IT",
    "SCHUFA Holding AG": "Banks & Finance",
    "Shazam Media Services GmbH": "Culture & Entertainment & Events",
    "Siemens Aktiengesellschaft": "IT",
    "Sigfox Germany GmbH": "Telecommunication",
    "Signavio GmbH": "IT",
    "Simplesurance GmbH": "Insurance",
    "smartly.io Solutions GmbH": "Marketing & Communications",
    "Smava GmbH": "Banks & Finance",
    "Socialbakers Germany GmbH": "Marketing & Communications",
    "solarisBank AG": "Banks & Finance",
    "Soundcloud Global Limited & Co KG": "Culture & Entertainment & Events",
    "SPIEGEL-Verlag Rudolf Augstein GmbH & Co. KG":
        "Culture & Entertainment & Events",
    "Spotahome Germany GmbH": "Sharing Economy",
    "Spotcap Global Services GmbH": "Banks & Finance",
    "Spotify GmbH": "Culture & Entertainment & Events",
    "Ströer SE & Co. KGaA": "Internet & Multimedia",
    "Tado GmbH": "Energy & Environment",
    "Ubisoft Blue Byte GmbH": "Culture & Entertainment & Events",
    "Verizon Media Germany GmbH": "Culture & Entertainment & Events",
    "wefox Germany GmbH": "Insurance",
    "Yelp Ireland Limited": "Retail & Consumption",
    "Zalando SE": "Retail & Consumption",
};
