export default {
    de: {
        "1 & 1 Ionos": "Telekommunikation",
        "ABOUT YOU GmbH": "Handel & Konsum",
        "Acronis Germany GmbH": "EDV & IT",
        "Ada Health GmbH": "Gesundheitswesen & Soziales",
        "AdColony GmbH": "Internet & Multimedia",
        "Adform Germany GmbH": "Internet & Multimedia",
        "Adidas AG": "Textil & Mode",
        "Allianz SE": "Versicherung",
        "Amazon Europe Core SARL": "Handel & Konsum",
        "APPLE INC.": "EDV & IT",
        "ASOS Germany GmbH": "Internet & Multimedia",
        "Auto 1 Group GmbH": "Internet & Multimedia",
        "auxmoney GmbH": "Banken & Finanzen",
        "Baker & McKenzie International B.V.": "Recht & Steuern",
        "BASF SE": "Chemie & Pharma",
        "Bayer AG": "Chemie & Pharma",
        "Blacklane GmbH": "Verkehr & Transport & Logistik",
        "Bayerische Motoren Werke AG": "Automotive",
        "BOOHOO GROUP PLC": "Handel & Konsum",
        "booking.com B.V.": "Internet & Multimedia",
        "Check24 Vergleichsportal GmbH": "Internet & Multimedia",
        "CLOUD & HEAT Technologies GmbH": "EDV & IT",
        "Comuto Deutschland GmbH": "Verkehr & Transport & Logistik",
        "Contentful GmbH": "Kultur & Unterhaltung & Veranstaltung",
        "DB Vertrieb GmbH": "Verkehr & Transport & Logistik",
        "Deliveroo Germany gmbH": "Handel & Konsum",
        "Delivery Hero SE": "Handel & Konsum",
        "Deposit Solutions GmbH": "Banken & Finanzen",
        "Doctolib GmbH": "Gesundheitswesen & Soziales",
        "Dreamlines Tours GmbH": "Verkehr & Transport & Logistik",
        "eGym GmbH": "Gesundheitswesen & Soziales",
        "FC Bayern München AG": "Kultur & Unterhaltung & Veranstaltung",
        "FinanceFox Beteiligung GmbH": "Banken & Finanzen",
        "FlixMobility GmbH": "Verkehr & Transport & Logistik",
        "GetYourGuide Deutschland GmbH": "Service",
        "GOEURO Travel GmbH": "Verkehr & Transport & Logistik",
        "Google LLC": "Internet & Multimedia",
        "Gruner + Jahr GmbH": "Kultur & Unterhaltung & Veranstaltung",
        "Hellofresh SE": "Handel & Konsum",
        "Helpling GmbH & Co. KG": "Service",
        "Inter IKEA Systems B.V.": "Handel & Konsum",
        "Immobilien Scout GmbH": "Immobilien & Facility Management",
        "Intel Deutschland GmbH": "EDV & IT",
        "Jobandtalent DE GmbH": "Service",
        "Klarna GmbH": "Banken & Finanzen",
        "Kreditech Holding SSL GmbH": "Banken & Finanzen",
        "Launchmetrics Germany GmbH": "Internet & Multimedia",
        "yd. yourdelivery GmbH": "Handel & Konsum",
        "MAINSTAY MEDICAL INTERNATIONAL PUBLIC LIMITED COMPANY":
            "Gesundheitswesen & Soziales",
        "MessageBird GmbH": "Internet & Multimedia",
        "mobile.de GmbH": "Handel & Konsum",
        "N26 Bank GmbH": "Banken & Finanzen",
        "Nestle S.A.": "Handel & Konsum",
        "Netflix International B.V.": "Kultur & Unterhaltung & Veranstaltung",
        "Otto (GmbH & Co KG)": "Handel & Konsum",
        "Outfittery GmbH": "Handel & Konsum",
        "Pro Sieben Sat.1 Media": "Kultur & Unterhaltung & Veranstaltung",
        "Raisin GmbH": "Banken & Finanzen",
        "ResearchGate GmbH": "Internet & Multimedia",
        "Roche Deutschland Holding GmbH": "Chemie & Pharma",
        "Rocket Internet SE": "Internet & Multimedia",
        "Samsung Electronics GmbH": "Internet & Multimedia",
        "SAP Deutschland SE & Co. KG": "EDV & IT",
        "SCHUFA Holding AG": "Banken & Finanzen",
        "Shazam Media Services GmbH": "Kultur & Unterhaltung & Veranstaltung",
        "Siemens Aktiengesellschaft": "EDV & IT",
        "Sigfox Germany GmbH": "Telekommunikation",
        "Signavio GmbH": "EDV & IT",
        "Simplesurance GmbH": "Versicherung",
        "smartly.io Solutions GmbH": "Marketing & Kommunikation",
        "Smava GmbH": "Banken & Finanzen",
        "Socialbakers Germany GmbH": "Marketing & Kommunikation",
        "solarisBank AG": "Banken & Finanzen",
        "Soundcloud Global Limited & Co KG":
            "Kultur & Unterhaltung & Veranstaltung",
        "SPIEGEL-Verlag Rudolf Augstein GmbH & Co. KG":
            "Kultur & Unterhaltung & Veranstaltung",
        "Spotahome Germany GmbH": "EDV & IT",
        "Spotcap Global Services GmbH": "Banken & Finanzen",
        "Spotify GmbH": "Kultur & Unterhaltung & Veranstaltung",
        "Ströer SE & Co. KGaA": "Internet & Multimedia",
        "Tado GmbH": "Energie & Umwelt",
        "Ubisoft Blue Byte GmbH": "Kultur & Unterhaltung & Veranstaltung",
        "Verizon Media Germany GmbH": "Kultur & Unterhaltung & Veranstaltung",
        "wefox Germany GmbH": "Versicherung",
        "Yelp Ireland Limited": "Handel & Konsum",
        "Zalando SE": "Handel & Konsum",
    },
    en: {
        "1 & 1 Ionos": "Telecommunication",
        "ABOUT YOU GmbH": "Retail & Consumption",
        "Acronis Germany GmbH": "IT",
        "Ada Health GmbH": "Health & Social",
        "AdColony GmbH": "Internet & Multimedia",
        "Adform Germany GmbH": "Internet & Multimedia",
        "Adidas AG": "Textile & Fashion",
        "Allianz SE": "Insurance",
        "Amazon Europe Core SARL": "Retail & Consumption",
        "APPLE INC.": "IT",
        "ASOS Germany GmbH": "Internet & Multimedia",
        "Auto 1 Group GmbH": "Internet & Multimedia",
        "auxmoney GmbH": "Banks & Finance",
        "Baker & McKenzie International B.V.": "Law & Taxes",
        "BASF SE": "Chemical & Pharmazeutical",
        "Bayer AG": "Chemical & Pharmazeutical",
        "Blacklane GmbH": "Traffic & Transport & Logistics",
        "Bayerische Motoren Werke AG": "Automotive",
        "BOOHOO GROUP PLC": "Retail & Consumption",
        "booking.com B.V.": "Internet & Multimedia",
        "Check24 Vergleichsportal GmbH": "Internet & Multimedia",
        "CLOUD & HEAT Technologies GmbH": "IT",
        "Comuto Deutschland GmbH": "Traffic & Transport & Logistics",
        "Contentful GmbH": "Culture & Entertainment & Events",
        "DB Vertrieb GmbH": "Traffic & Transport & Logistics",
        "Deliveroo Germany gmbH": "Retail & Consumption",
        "Delivery Hero SE": "Retail & Consumption",
        "Deposit Solutions GmbH": "Banks & Finance",
        "Doctolib GmbH": "Health & Social",
        "Dreamlines Tours GmbH": "Traffic & Transport & Logistics",
        "eGym GmbH": "Health & Social",
        "FC Bayern München AG": "Culture & Entertainment & Events",
        "FinanceFox Beteiligung GmbH": "Banks & Finance",
        "FlixMobility GmbH": "Traffic & Transport & Logistics",
        "GetYourGuide Deutschland GmbH": "Service",
        "GOEURO Travel GmbH": "Traffic & Transport & Logistics",
        "Google LLC": "Internet & Multimedia",
        "Gruner + Jahr GmbH": "Culture & Entertainment & Events",
        "Hellofresh SE": "Retail & Consumption",
        "Helpling GmbH & Co. KG": "Service",
        "Inter IKEA Systems B.V.": "Retail & Consumption",
        "Immobilien Scout GmbH": "Real Estate & Facility Management",
        "Intel Deutschland GmbH": "IT",
        "Jobandtalent DE GmbH": "Service",
        "Klarna GmbH": "Banks & Finance",
        "Kreditech Holding SSL GmbH": "Banks & Finance",
        "Launchmetrics Germany GmbH": "Internet & Multimedia",
        "yd. yourdelivery GmbH": "Retail & Consumption",
        "MAINSTAY MEDICAL INTERNATIONAL PUBLIC LIMITED COMPANY":
            "Health & Social",
        "MessageBird GmbH": "Internet & Multimedia",
        "mobile.de GmbH": "Retail & Consumption",
        "N26 Bank GmbH": "Banks & Finance",
        "Nestle S.A.": "Retail & Consumption",
        "Netflix International B.V.": "Culture & Entertainment & Events",
        "Otto (GmbH & Co KG)": "Retail & Consumption",
        "Outfittery GmbH": "Retail & Consumption",
        "Pro Sieben Sat.1 Media": "Culture & Entertainment & Events",
        "Raisin GmbH": "Banks & Finance",
        "ResearchGate GmbH": "Internet & Multimedia",
        "Roche Deutschland Holding GmbH": "Chemical & Pharmazeutical",
        "Rocket Internet SE": "Internet & Multimedia",
        "Samsung Electronics GmbH": "Internet & Multimedia",
        "SAP Deutschland SE & Co. KG": "IT",
        "SCHUFA Holding AG": "Banks & Finance",
        "Shazam Media Services GmbH": "Culture & Entertainment & Events",
        "Siemens Aktiengesellschaft": "IT",
        "Sigfox Germany GmbH": "Telecommunication",
        "Signavio GmbH": "IT",
        "Simplesurance GmbH": "Insurance",
        "smartly.io Solutions GmbH": "Marketing & Communications",
        "Smava GmbH": "Banks & Finance",
        "Socialbakers Germany GmbH": "Marketing & Communications",
        "solarisBank AG": "Banks & Finance",
        "Soundcloud Global Limited & Co KG": "Culture & Entertainment & Events",
        "SPIEGEL-Verlag Rudolf Augstein GmbH & Co. KG":
            "Culture & Entertainment & Events",
        "Spotahome Germany GmbH": "Sharing Economy",
        "Spotcap Global Services GmbH": "Banks & Finance",
        "Spotify GmbH": "Culture & Entertainment & Events",
        "Ströer SE & Co. KGaA": "Internet & Multimedia",
        "Tado GmbH": "Energy & Environment",
        "Ubisoft Blue Byte GmbH": "Culture & Entertainment & Events",
        "Verizon Media Germany GmbH": "Culture & Entertainment & Events",
        "wefox Germany GmbH": "Insurance",
        "Yelp Ireland Limited": "Retail & Consumption",
        "Zalando SE": "Retail & Consumption",
    },
};
