version: 2
updates:

  # Check dependencies for GitHub Actions.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Check gradle dependencies.
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "daily"

  # Check gradle dependencies.
  - package-ecosystem: "gradle"
    directory: "/android/app"
    schedule:
      interval: "daily"

  # Check gradle dependencies.
  - package-ecosystem: "gradle"
    directory: "/android/java-fetch"
    schedule:
      interval: "daily"

  # Check gradle dependencies.
  - package-ecosystem: "gradle"
    directory: "/android/polyOut"
    schedule:
      interval: "daily"

  # Check gradle dependencies.
  - package-ecosystem: "gradle"
    directory: "/core/communication/bubblewrap"
    schedule:
      interval: "daily"

  # Check npm dependencies.
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  # Check npm dependencies.
  - package-ecosystem: "npm"
    directory: "/android/java-fetch"
    schedule:
      interval: "daily"

  # Check npm dependencies.
  - package-ecosystem: "npm"
    directory: "/build"
    schedule:
      interval: "daily"

  # Check npm dependencies.
  - package-ecosystem: "npm"
    directory: "/core/api/fetch-spec"
    schedule:
      interval: "daily"

  # Check npm dependencies.
  - package-ecosystem: "npm"
    directory: "/core/api/manifest-parser"
    schedule:
      interval: "daily"

  # Check npm dependencies.
  - package-ecosystem: "npm"
    directory: "/core/api/pod-api"
    schedule:
      interval: "daily"

  # Check npm dependencies.
  - package-ecosystem: "npm"
    directory: "/core/api/rdf"
    schedule:
      interval: "daily"

  # Check npm dependencies.
  - package-ecosystem: "npm"
    directory: "/core/api/rdf-convert"
    schedule:
      interval: "daily"

  # Check npm dependencies.
  - package-ecosystem: "npm"
    directory: "/core/api/rdf-spec"
    schedule:
      interval: "daily"

  # Check npm dependencies.
  - package-ecosystem: "npm"
    directory: "/core/communication/bubblewrap"
    schedule:
      interval: "daily"

  # Check npm dependencies.
  - package-ecosystem: "npm"
    directory: "/core/communication/port-authority"
    schedule:
      interval: "daily"

  # Check npm dependencies.
  - package-ecosystem: "npm"
    directory: "/core/communication/postoffice"
    schedule:
      interval: "daily"

  # Check npm dependencies.
  - package-ecosystem: "npm"
    directory: "/core/communication/remote-pod"
    schedule:
      interval: "daily"

  # Check npm dependencies.
  - package-ecosystem: "npm"
    directory: "/core/utils/dummy-server"
    schedule:
      interval: "daily"

  # Check npm dependencies.
  - package-ecosystem: "npm"
    directory: "/core/utils/poly-look"
    schedule:
      interval: "daily"

  # Check npm dependencies.
  - package-ecosystem: "npm"
    directory: "/core/utils/rollup-plugin-copy-watch"
    schedule:
      interval: "daily"

  # Check npm dependencies.
  - package-ecosystem: "npm"
    directory: "/core/utils/silly-i18n"
    schedule:
      interval: "daily"

  # Check npm dependencies.
  - package-ecosystem: "npm"
    directory: "/features/bundle"
    schedule:
      interval: "daily"

  # Check npm dependencies.
  - package-ecosystem: "npm"
    directory: "/features/example"
    schedule:
      interval: "daily"

  # Check npm dependencies.
  - package-ecosystem: "npm"
    directory: "/features/facebookImport"
    schedule:
      interval: "daily"

  # Check npm dependencies.
  - package-ecosystem: "npm"
    directory: "/features/lexicon"
    schedule:
      interval: "daily"

  # Check npm dependencies.
  - package-ecosystem: "npm"
    directory: "/features/polyExplorer"
    schedule:
      interval: "daily"

  # Check npm dependencies.
  - package-ecosystem: "npm"
    directory: "/features/polyExplorer/node_modules/babel-code-frame"
    schedule:
      interval: "daily"

  # Check npm dependencies.
  - package-ecosystem: "npm"
    directory: "/features/polyPinion"
    schedule:
      interval: "daily"

  # Check npm dependencies.
  - package-ecosystem: "npm"
    directory: "/features/polyPreview"
    schedule:
      interval: "daily"

  # Check npm dependencies.
  - package-ecosystem: "npm"
    directory: "/features/test"
    schedule:
      interval: "daily"

  # Check npm dependencies.
  - package-ecosystem: "npm"
    directory: "/podjs"
    schedule:
      interval: "daily"
