disabled_rules:
    - trailing_whitespace
    - force_cast #FIX!
    - todo
    - identifier_name
    - force_try #FIX!

opt_in_rules:
    - empty_string
    - empty_count
    - empty_xctest_method
    - fatal_error_message
    - last_where
    - private_action
    - prohibited_interface_builder
    - return_value_from_void_function
    - unavailable_function
    - identical_operands
    - joined_default_parameter
    - fallthrough
    - modifier_order
    - unused_declaration
    - unused_import
    - toggle_bool
    - yoda_condition
    - prefer_self_in_static_references
    - prefer_self_type_over_type_of_self
    - private_outlet
    - quick_discouraged_call
    - quick_discouraged_focused_test
    - quick_discouraged_pending_test
    - sorted_imports
    - static_operator
    - strong_iboutlet
    - test_case_accessibility
    - unowned_variable_capture
    - array_init
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - contains_over_range_nil_comparison
    - literal_expression_end_indentation
