disabled_rules:
    - trailing_whitespace
    - force_cast #FIX!
    - todo
    - identifier_name
    - force_try #FIX!

opt_in_rules:
    - empty_string
    - empty_count
    - empty_xctest_method
    - unused_private_declaration
    - fatal_error_message
    - last_where
    - private_action
    - prohibited_interface_builder
    - return_value_from_void_function
    - unavailable_function
    - identical_operands
    - joined_default_parameter
    - fallthrough
    - modifier_order
    - unused_declaration
    - toggle_bool
    - yoda_condition
