# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PolyPod' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PolyPod
  pod 'MatrixSDK'

  target 'PolyPodTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PolyPodUITests' do
    # Pods for testing
  end

end
