export default {
    questionnaire: {
        _id: "e0d11a9b-5b21-41b1-ae63-79359dc029b1",
        _date_generated: "2020-05-22T10:33:17.106Z",
        _title: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:meta.title",
        _description: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:meta.description",
        _published_date: "2020-05-22T11:00:00.000Z",
        _author: {
            _name: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:meta.author.name",
            _link: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:meta.author.link",
            _description:
                "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:meta.author.description",
            _logo:
                '<svg viewBox="0 0 228 111" fill="none" xmlns="http://www.w3.org/2000/svg">\r\n<path d="M60.6506 13.6423H68.1919V16.0269C70.4978 14.1443 73.4271 13.0775 76.7303 13.0775C84.6454 13.0775 91.0025 19.7293 91.0025 28.3892C91.0025 32.4054 89.6313 35.9823 87.3254 38.6807C84.7701 41.6928 80.5944 43.6381 76.294 43.6381C73.3648 43.6381 70.8095 42.8224 68.5035 41.0025V57.5693H60.713V13.6423H60.6506ZM68.5035 32.7192C69.9993 34.9155 72.6169 36.3588 75.5461 36.3588C79.9088 36.3588 83.212 32.9702 83.212 28.3892C83.212 24.1848 80.2827 20.3568 75.6707 20.3568C72.6792 20.3568 70.0616 21.8002 68.4411 23.9965V32.7192H68.5035Z" />\r\n<path d="M111.32 13.0775C120.17 13.0775 126.839 19.9176 126.839 28.3892C126.839 36.8608 120.17 43.6381 111.32 43.6381C102.47 43.6381 95.8013 36.8608 95.8013 28.3892C95.8013 19.9176 102.532 13.0775 111.32 13.0775ZM111.32 36.3588C115.87 36.3588 118.986 32.7819 118.986 28.3892C118.986 23.9965 115.87 20.3568 111.32 20.3568C106.77 20.3568 103.654 23.9965 103.654 28.3892C103.654 32.7819 106.77 36.3588 111.32 36.3588Z" />\r\n<path d="M141.236 0.0249023H133.445V43.0106H141.236V0.0249023Z" />\r\n<path d="M151.332 57.5065L159.435 40.0612L146.346 13.6423H154.947L163.486 31.2759L171.401 13.6423H179.628L159.559 57.5065H151.332Z" />\r\n<path d="M141.298 96.7271H133.757V94.3425C131.451 96.2251 128.522 97.2919 125.219 97.2919C117.303 97.2919 110.946 90.6401 110.946 81.9802C110.946 77.964 112.317 74.3871 114.623 71.6887C117.179 68.6765 121.354 66.7312 125.655 66.7312C128.584 66.7312 131.139 67.6097 133.445 69.3668V52.8628H141.236V96.7271H141.298ZM133.445 77.6502C131.95 75.4539 129.332 74.0105 126.403 74.0105C122.04 74.0105 118.737 77.3992 118.737 81.9802C118.737 86.2474 121.666 90.0125 126.278 90.0125C129.27 90.0125 131.887 88.5692 133.508 86.3729V77.6502H133.445Z" />\r\n<path d="M90.6286 97.2918C81.7785 97.2918 75.1099 90.4518 75.1099 81.9801C75.1099 73.5085 81.7785 66.7312 90.6286 66.7312C99.4786 66.7312 106.147 73.5085 106.147 81.9801C106.147 90.4518 99.4786 97.2918 90.6286 97.2918ZM90.6286 74.0105C86.0789 74.0105 82.9627 77.5874 82.9627 81.9801C82.9627 86.3728 86.0789 90.0125 90.6286 90.0125C95.1782 90.0125 98.2944 86.3728 98.2944 81.9801C98.2944 77.5874 95.1782 74.0105 90.6286 74.0105Z" />\r\n<path d="M68.5032 67.3587H60.7126V110.344H68.5032V67.3587Z" />\r\n<path d="M50.6164 52.8628L42.5766 70.3081L55.6023 96.7271H47.0016L38.4632 79.0935L30.6103 96.7271H22.3835L42.4519 52.8628H50.6164Z" />\r\n<path d="M0.881836 23.7455V85.7453H8.98398H19.2675L23.0069 77.5247H8.98398V31.9034H52.2993V23.7455H0.881836Z" />\r\n<path d="M220.824 23.6827H183.118L179.378 31.9033H219.079L219.016 77.5247L191.469 77.5874L171.089 77.5247L181.497 67.2959H172.024L157.627 81.5408L172.024 96.0995L181.497 96.1622L171.089 85.6198L227.118 85.6825V23.6827H220.824Z" />\r\n</svg>\r\n',
            __class__: "PpAuthor",
        },
        _legal: {
            _content: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:meta.legal.content",
            _link: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:meta.legal.link",
            __class__: "PpLegal",
        },
        _questions: [
            {
                _id: 1,
                _index: 0,
                _description: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:usage-01.q",
                _activationCondition: { _question: null, __class__: "PpTrueCondition" },
                _explanation: "general.choose-one",
                _questionnaire: "e0d11a9b-5b21-41b1-ae63-79359dc029b1",
                _choices: [
                    {
                        _id: 2,
                        _question: null,
                        _index: 0,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:usage-01.o01",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 3,
                        _question: null,
                        _index: 1,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:usage-01.o02",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 4,
                        _question: null,
                        _index: 2,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:usage-01.o03",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 5,
                        _question: null,
                        _index: 3,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:usage-01.o04",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 6,
                        _question: null,
                        _index: 4,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:usage-01.o05",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 7,
                        _question: null,
                        _index: 5,
                        _enabled: true,
                        is_selected: false,
                        _description: "general.none-above",
                        __class__: "PpTextualChoice",
                    },
                ],
                exclusion_groups: [[0, 1, 2, 3, 4], [5]],
                __class__: "PpSingleChoiceQuestion",
            },
            {
                _id: 8,
                _index: 1,
                _description: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:companies-01.q",
                _activationCondition: { _question: null, __class__: "PpTrueCondition" },
                _explanation: "general.select-all-apply",
                _questionnaire: "e0d11a9b-5b21-41b1-ae63-79359dc029b1",
                _choices: [
                    {
                        _id: 9,
                        _question: null,
                        _index: 0,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:companies-01.o01",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 10,
                        _question: null,
                        _index: 1,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:companies-01.o02",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 11,
                        _question: null,
                        _index: 2,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:companies-01.o03",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 12,
                        _question: null,
                        _index: 3,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:companies-01.o04",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 13,
                        _question: null,
                        _index: 4,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:companies-01.o05",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 14,
                        _question: null,
                        _index: 5,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:companies-01.o06",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 15,
                        _question: null,
                        _index: 6,
                        _enabled: true,
                        is_selected: false,
                        _description: "general.none-above",
                        __class__: "PpTextualChoice",
                    },
                ],
                _max_selections_allowed: null,
                _exclusion_groups: [[0, 1, 2, 3, 4, 5], [6]],
                __class__: "PpMultipleChoiceQuestion",
            },
            {
                _id: 16,
                _index: 2,
                _description: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:companies-02.q",
                _activationCondition: { _question: null, __class__: "PpTrueCondition" },
                _explanation: "general.select-all-apply",
                _questionnaire: "e0d11a9b-5b21-41b1-ae63-79359dc029b1",
                _choices: [
                    {
                        _id: 17,
                        _question: null,
                        _index: 0,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:companies-02.o01",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 18,
                        _question: null,
                        _index: 1,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:companies-02.o02",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 19,
                        _question: null,
                        _index: 2,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:companies-02.o03",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 20,
                        _question: null,
                        _index: 3,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:companies-02.o04",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 21,
                        _question: null,
                        _index: 4,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:companies-02.o05",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 22,
                        _question: null,
                        _index: 5,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:companies-02.o06",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 23,
                        _question: null,
                        _index: 6,
                        _enabled: true,
                        is_selected: false,
                        _description: "general.none-above",
                        __class__: "PpTextualChoice",
                    },
                ],
                _max_selections_allowed: null,
                _exclusion_groups: [[0, 1, 2, 3, 4, 5], [6]],
                __class__: "PpMultipleChoiceQuestion",
            },
            {
                _id: 24,
                _index: 3,
                _description: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:shopping-01.q",
                _activationCondition: { _question: null, __class__: "PpTrueCondition" },
                _explanation: "general.select-all-apply",
                _questionnaire: "e0d11a9b-5b21-41b1-ae63-79359dc029b1",
                _choices: [
                    {
                        _id: 25,
                        _question: null,
                        _index: 0,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:shopping-01.o01",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 26,
                        _question: null,
                        _index: 1,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:shopping-01.o02",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 27,
                        _question: null,
                        _index: 2,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:shopping-01.o03",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 28,
                        _question: null,
                        _index: 3,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:shopping-01.o04",
                        __class__: "PpTextualChoice",
                    },
                ],
                __class__: "PpSingleChoiceQuestion",
            },
            {
                _id: 29,
                _index: 4,
                _description: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:trust-01.q",
                _activationCondition: { _question: null, __class__: "PpTrueCondition" },
                _explanation: "general.choose-seat",
                _questionnaire: "e0d11a9b-5b21-41b1-ae63-79359dc029b1",
                _min: 1,
                _max: 5,
                _steps: 1,
                _labels: ["general.not-at-all", "general.completely"],
                _value: null,
                __class__: "PpRangeQuestion",
            },
            {
                _id: 30,
                _index: 5,
                _description: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:trust-02.q",
                _activationCondition: { _question: null, __class__: "PpTrueCondition" },
                _explanation: "general.choose-seat",
                _questionnaire: "e0d11a9b-5b21-41b1-ae63-79359dc029b1",
                _min: 1,
                _max: 5,
                _steps: 1,
                _labels: ["general.not-at-all", "general.completely"],
                _value: null,
                __class__: "PpRangeQuestion",
            },
            {
                _id: 31,
                _index: 6,
                _description: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:trust-03.q",
                _activationCondition: { _question: null, __class__: "PpTrueCondition" },
                _explanation: "general.choose-seat",
                _questionnaire: "e0d11a9b-5b21-41b1-ae63-79359dc029b1",
                _min: 1,
                _max: 5,
                _steps: 1,
                _labels: ["general.not-at-all", "general.completely"],
                _value: null,
                __class__: "PpRangeQuestion",
            },
            {
                _id: 32,
                _index: 7,
                _description: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:trust-04.q",
                _activationCondition: { _question: null, __class__: "PpTrueCondition" },
                _explanation: "general.choose-seat",
                _questionnaire: "e0d11a9b-5b21-41b1-ae63-79359dc029b1",
                _min: 1,
                _max: 5,
                _steps: 1,
                _labels: ["general.not-at-all", "general.completely"],
                _value: null,
                __class__: "PpRangeQuestion",
            },
            {
                _id: 33,
                _index: 8,
                _description: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:uscomfort-01.q",
                _activationCondition: { _question: null, __class__: "PpTrueCondition" },
                _explanation: "general.choose-seat",
                _questionnaire: "e0d11a9b-5b21-41b1-ae63-79359dc029b1",
                _min: 1,
                _max: 5,
                _steps: 1,
                _labels: ["general.not-at-all", "general.very"],
                _value: null,
                __class__: "PpRangeQuestion",
            },
            {
                _id: 34,
                _index: 9,
                _description: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:trust-05.q",
                _activationCondition: { _question: null, __class__: "PpTrueCondition" },
                _explanation: "general.choose-seat",
                _questionnaire: "e0d11a9b-5b21-41b1-ae63-79359dc029b1",
                _min: 1,
                _max: 5,
                _steps: 1,
                _labels: ["general.not-at-all", "general.completely"],
                _value: null,
                __class__: "PpRangeQuestion",
            },
            {
                _id: 35,
                _index: 10,
                _description: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:gdpr-01.q",
                _activationCondition: { _question: null, __class__: "PpTrueCondition" },
                _explanation: "general.choose-one",
                _questionnaire: "e0d11a9b-5b21-41b1-ae63-79359dc029b1",
                _choices: [
                    {
                        _id: 36,
                        _question: null,
                        _index: 0,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:gdpr-01.o01",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 37,
                        _question: null,
                        _index: 1,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:gdpr-01.o02",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 38,
                        _question: null,
                        _index: 2,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:gdpr-01.o03",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 39,
                        _question: null,
                        _index: 3,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:gdpr-01.o04",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 40,
                        _question: null,
                        _index: 4,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:gdpr-01.o05",
                        __class__: "PpTextualChoice",
                    },
                ],
                __class__: "PpSingleChoiceQuestion",
            },
            {
                _id: 41,
                _index: 11,
                _description: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:gdpr-02.q",
                _activationCondition: { _question: null, __class__: "PpTrueCondition" },
                _explanation: "general.choose-one",
                _questionnaire: "e0d11a9b-5b21-41b1-ae63-79359dc029b1",
                _choices: [
                    {
                        _id: 42,
                        _question: null,
                        _index: 0,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:gdpr-02.o01",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 43,
                        _question: null,
                        _index: 1,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:gdpr-02.o02",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 44,
                        _question: null,
                        _index: 2,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:gdpr-02.o03",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 45,
                        _question: null,
                        _index: 3,
                        _enabled: true,
                        is_selected: false,
                        _description: "general.i-dont-know",
                        __class__: "PpTextualChoice",
                    },
                ],
                __class__: "PpSingleChoiceQuestion",
            },
            {
                _id: 46,
                _index: 12,
                _description: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:control-13.q",
                _activationCondition: { _question: null, __class__: "PpTrueCondition" },
                _explanation: "general.select-all-apply",
                _questionnaire: "e0d11a9b-5b21-41b1-ae63-79359dc029b1",
                _choices: [
                    {
                        _id: 47,
                        _question: null,
                        _index: 0,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:control-13.o01",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 48,
                        _question: null,
                        _index: 1,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:control-13.o02",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 49,
                        _question: null,
                        _index: 2,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:control-13.o03",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 50,
                        _question: null,
                        _index: 3,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:control-13.o04",
                        __class__: "PpTextualChoice",
                    },
                ],
                _max_selections_allowed: null,
                _exclusion_groups: [],
                __class__: "PpMultipleChoiceQuestion",
            },
            {
                _id: 51,
                _index: 13,
                _description: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:empowered-14.q",
                _activationCondition: { _question: null, __class__: "PpTrueCondition" },
                _explanation: "general.choose-seat",
                _questionnaire: "e0d11a9b-5b21-41b1-ae63-79359dc029b1",
                _min: 1,
                _max: 5,
                _steps: 1,
                _labels: ["general.not-at-all", "general.very"],
                _value: null,
                __class__: "PpRangeQuestion",
            },
            {
                _id: 52,
                _index: 14,
                _description: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:affected-15.q",
                _activationCondition: { _question: null, __class__: "PpTrueCondition" },
                _explanation: "general.choose-one",
                _questionnaire: "e0d11a9b-5b21-41b1-ae63-79359dc029b1",
                _choices: [
                    {
                        _id: 53,
                        _question: null,
                        _index: 0,
                        _enabled: true,
                        is_selected: false,
                        _description: "general.yes",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 54,
                        _question: null,
                        _index: 1,
                        _enabled: true,
                        is_selected: false,
                        _description: "general.no",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 55,
                        _question: null,
                        _index: 2,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:affected-15.o03",
                        __class__: "PpTextualChoice",
                    },
                ],
                __class__: "PpSingleChoiceQuestion",
            },
            {
                _id: 56,
                _index: 15,
                _description: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:affected-16.q",
                _activationCondition: { _question: null, __class__: "PpTrueCondition" },
                _explanation: "general.enter-answer-below",
                _questionnaire: "e0d11a9b-5b21-41b1-ae63-79359dc029b1",
                _answer: null,
                _max_length: 280,
                _multiline: true,
                _number_of_lines: 3,
                _one_word_validation: false,
                __class__: "PpTextQuestion",
            },
            {
                _id: 57,
                _index: 16,
                _description: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:protected-17.q",
                _activationCondition: { _question: null, __class__: "PpTrueCondition" },
                _explanation: "general.choose-seat",
                _questionnaire: "e0d11a9b-5b21-41b1-ae63-79359dc029b1",
                _min: 1,
                _max: 5,
                _steps: 1,
                _labels: ["general.not-at-all", "general.very"],
                _value: null,
                __class__: "PpRangeQuestion",
            },
            {
                _id: 58,
                _index: 17,
                _description: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:priority-18.q",
                _activationCondition: { _question: null, __class__: "PpTrueCondition" },
                _explanation: "general.choose-one",
                _questionnaire: "e0d11a9b-5b21-41b1-ae63-79359dc029b1",
                _choices: [
                    {
                        _id: 59,
                        _question: null,
                        _index: 0,
                        _enabled: true,
                        is_selected: false,
                        _description: "general.yes",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 60,
                        _question: null,
                        _index: 1,
                        _enabled: true,
                        is_selected: false,
                        _description: "general.no",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 61,
                        _question: null,
                        _index: 2,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:priority-18.o03",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 62,
                        _question: null,
                        _index: 3,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:priority-18.o04",
                        __class__: "PpTextualChoice",
                    },
                ],
                __class__: "PpSingleChoiceQuestion",
            },
            {
                _id: 63,
                _index: 18,
                _description: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:value-19.q",
                _activationCondition: { _question: null, __class__: "PpTrueCondition" },
                _explanation: "general.choose-one",
                _questionnaire: "e0d11a9b-5b21-41b1-ae63-79359dc029b1",
                _choices: [
                    {
                        _id: 64,
                        _question: null,
                        _index: 0,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:value-19.o01",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 65,
                        _question: null,
                        _index: 1,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:value-19.o02",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 66,
                        _question: null,
                        _index: 2,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:value-19.o03",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 67,
                        _question: null,
                        _index: 3,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:value-19.o04",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 68,
                        _question: null,
                        _index: 4,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:value-19.o05",
                        __class__: "PpTextualChoice",
                    },
                ],
                __class__: "PpSingleChoiceQuestion",
            },
            {
                _id: 69,
                _index: 19,
                _description: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:share-20.q",
                _activationCondition: { _question: null, __class__: "PpTrueCondition" },
                _explanation: "general.choose-one",
                _questionnaire: "e0d11a9b-5b21-41b1-ae63-79359dc029b1",
                _choices: [
                    {
                        _id: 70,
                        _question: null,
                        _index: 0,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:share-20.o01",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 71,
                        _question: null,
                        _index: 1,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:share-20.o02",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 72,
                        _question: null,
                        _index: 2,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:share-20.o03",
                        __class__: "PpTextualChoice",
                    },
                ],
                __class__: "PpSingleChoiceQuestion",
            },
            {
                _id: 73,
                _index: 20,
                _description: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:access-21.q",
                _activationCondition: { _question: null, __class__: "PpTrueCondition" },
                _explanation: "general.select-all-apply",
                _questionnaire: "e0d11a9b-5b21-41b1-ae63-79359dc029b1",
                _choices: [
                    {
                        _id: 74,
                        _question: null,
                        _index: 0,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:access-21.o01",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 75,
                        _question: null,
                        _index: 1,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:access-21.o02",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 76,
                        _question: null,
                        _index: 2,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:access-21.o03",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 77,
                        _question: null,
                        _index: 3,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:access-21.o04",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 78,
                        _question: null,
                        _index: 4,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:access-21.o05",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 79,
                        _question: null,
                        _index: 5,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:access-21.o06",
                        __class__: "PpTextualChoice",
                    },
                ],
                _max_selections_allowed: null,
                _exclusion_groups: [[0, 1, 2, 3, 4], [5]],
                __class__: "PpMultipleChoiceQuestion",
            },
            {
                _id: 80,
                _index: 21,
                _description: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:TaCs-22.q",
                _activationCondition: { _question: null, __class__: "PpTrueCondition" },
                _explanation: "general.choose-one",
                _questionnaire: "e0d11a9b-5b21-41b1-ae63-79359dc029b1",
                _choices: [
                    {
                        _id: 81,
                        _question: null,
                        _index: 0,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:TaCs-22.o01",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 82,
                        _question: null,
                        _index: 1,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:TaCs-22.o02",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 83,
                        _question: null,
                        _index: 2,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:TaCs-22.o03",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 84,
                        _question: null,
                        _index: 3,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:TaCs-22.o04",
                        __class__: "PpTextualChoice",
                    },
                ],
                __class__: "PpSingleChoiceQuestion",
            },
            {
                _id: 85,
                _index: 22,
                _description: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:familiar-23.q",
                _activationCondition: { _question: null, __class__: "PpTrueCondition" },
                _explanation: "general.select-all-apply",
                _questionnaire: "e0d11a9b-5b21-41b1-ae63-79359dc029b1",
                _choices: [
                    {
                        _id: 86,
                        _question: null,
                        _index: 0,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:familiar-23.o01",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 87,
                        _question: null,
                        _index: 1,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:familiar-23.o02",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 88,
                        _question: null,
                        _index: 2,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:familiar-23.o03",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 89,
                        _question: null,
                        _index: 3,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:familiar-23.o04",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 90,
                        _question: null,
                        _index: 4,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:familiar-23.o05",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 91,
                        _question: null,
                        _index: 5,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:familiar-23.o06",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 92,
                        _question: null,
                        _index: 6,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:familiar-23.o07",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 93,
                        _question: null,
                        _index: 7,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:familiar-23.o08",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 94,
                        _question: null,
                        _index: 8,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:familiar-23.o09",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 95,
                        _question: null,
                        _index: 9,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:familiar-23.o10",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 96,
                        _question: null,
                        _index: 10,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:familiar-23.o11",
                        __class__: "PpTextualChoice",
                    },
                ],
                _max_selections_allowed: null,
                _exclusion_groups: [],
                __class__: "PpMultipleChoiceQuestion",
            },
            {
                _id: 97,
                _index: 23,
                _description: "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.q",
                _activationCondition: { _question: null, __class__: "PpTrueCondition" },
                _explanation: "general.select-all-apply",
                _questionnaire: "e0d11a9b-5b21-41b1-ae63-79359dc029b1",
                _choices: [
                    {
                        _id: 98,
                        _question: null,
                        _index: 0,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o01",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 99,
                        _question: null,
                        _index: 1,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o02",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 100,
                        _question: null,
                        _index: 2,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o03",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 101,
                        _question: null,
                        _index: 3,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o04",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 102,
                        _question: null,
                        _index: 4,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o05",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 103,
                        _question: null,
                        _index: 5,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o06",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 104,
                        _question: null,
                        _index: 6,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o07",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 105,
                        _question: null,
                        _index: 7,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o08",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 106,
                        _question: null,
                        _index: 8,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o09",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 107,
                        _question: null,
                        _index: 9,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o10",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 108,
                        _question: null,
                        _index: 10,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o11",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 109,
                        _question: null,
                        _index: 11,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o12",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 110,
                        _question: null,
                        _index: 12,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o13",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 111,
                        _question: null,
                        _index: 13,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o14",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 112,
                        _question: null,
                        _index: 14,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o15",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 113,
                        _question: null,
                        _index: 15,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o16",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 114,
                        _question: null,
                        _index: 16,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o17",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 115,
                        _question: null,
                        _index: 17,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o18",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 116,
                        _question: null,
                        _index: 18,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o19",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 117,
                        _question: null,
                        _index: 19,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o20",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 118,
                        _question: null,
                        _index: 20,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o21",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 119,
                        _question: null,
                        _index: 21,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o22",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 120,
                        _question: null,
                        _index: 22,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o23",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 121,
                        _question: null,
                        _index: 23,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o24",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 122,
                        _question: null,
                        _index: 24,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o25",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 123,
                        _question: null,
                        _index: 25,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o26",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 124,
                        _question: null,
                        _index: 26,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o27",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 125,
                        _question: null,
                        _index: 27,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o28",
                        __class__: "PpTextualChoice",
                    },
                    {
                        _id: 126,
                        _question: null,
                        _index: 28,
                        _enabled: true,
                        is_selected: false,
                        _description:
                            "questionnaire-e0d11a9b-5b21-41b1-ae63-79359dc029b1:country-01.o29",
                        __class__: "PpTextualChoice",
                    },
                ],
                __class__: "PpSingleChoiceQuestion",
            },
        ],
        _available_translations: { english: "en", german: "de" },
        _submission_deadline: "2020-06-15T21:59:59.000Z",
        _encryption_public_key: "9j2SyrInwXWz4iqCQNid0VadFjDBDs4fGtZH+h1u71I=",
        _result: null,
        _schema: "v1",
        __class__: "PpQuestionnaire",
    },
    languages: {
        de: {
            meta: {
                title: "Vertrauen und die Datenökonomie",
                description:
                    "Wie viel Vertrauen haben wir in die Datenökonomie? Diese Umfrage soll helfen, dieses Feld besser zu verstehen.\n\nUnd, noch viel wichtiger, uns selbst.",
                legal: {
                    content:
                        "Diese Umfrage wird von uns selbst (polypoly GmbH) durchgeführt. In ihr erfassen wir keinerlei private oder personenbezogene Daten. Die von Dir hochgeladenen Antworten werden anonym gespeichert, ohne jegliche Verbindung zu Dir, Deinem Telefon oder der darauf installierten App.\n\nFür mehr Informationen zum polyPod besuche bitte unsere Webseite:\n\n<1>https://pod.polypoly.eu</1>",
                    link: "https://pod.polypoly.eu",
                },
                author: {
                    name: "polypoly",
                    link: "https://polypoly.eu/de/home",
                    description:
                        "Wir sind die Macher des polyPods, ein digitales Ökosystem das Menschen hilft, die Kontrolle über ihre Daten zurückzuerhalten. Wir bauen Produkte, die Dir helfen, und dabei die Datenhoheit zurück nach Europa bringen.\n\nWir setzen auf Datenschutz by Design, digitalen Pluralismus und das Individuum.\n\nFolge uns auf Twitter @polypolyEU für mehr Informationen über diese Dinge.",
                },
            },
            "usage-01": {
                q: "Wie würdest du deinen Internetkonsum beschreiben?",
                o01: "Ich benutze es hauptsächlich für die Kommunikation auf der Arbeit",
                o02: "Ich benutze es für meine tägliche Arbeit im Büro",
                o03: "Ich benutze es für die tägliche Arbeit und zum Austausch mit Freunden",
                o04:
                    "Ich benutze es für die tägliche Arbeit, zum Austausch mit Freunden und fürs Shoppen",
                o05:
                    "Ich benutze es für die tägliche Arbeit, zum Austausch mit Freunden, fürs Shoppen und zur Unterhaltung",
            },
            "companies-01": {
                q: "Welche der folgenden Dienste und Firmenseiten benutzt du für die Arbeit?",
                o01: "Google",
                o02: "Facebook (inklusive Instagram und WhatsApp)",
                o03: "Amazon",
                o04: "Apple",
                o05: "Microsoft",
                o06: "Twitter",
            },
            "companies-02": {
                q: "Welche der Folgenden Dienste und Firmenseiten benutzt du privat?",
                o01: "Google",
                o02: "Facebook (inklusive Instagram und WhatsApp)",
                o03: "Amazon",
                o04: "Apple",
                o05: "Microsoft",
                o06: "Twitter",
            },
            "shopping-01": {
                q: "Wie viele Einkäufe tätigst du online?",
                o01: "Keine",
                o02: "Manche",
                o03: "Mehr als die Hälfte",
                o04: "Fast alle",
            },
            "trust-01": {
                q:
                    "Wie viel Vertrauen hast du in Facebook, deine personenbezogenen Daten zu schützen?",
            },
            "trust-02": {
                q:
                    "Wie viel Vertrauen hast du in Google, deine personenbezogenen Daten zu schützen?",
            },
            "trust-03": {
                q:
                    "Wie viel Vertrauen hast du in Apple, deine personenbezogenen Daten zu schützen?",
            },
            "trust-04": {
                q:
                    "Wie viel Vertrauen hast du in Amazon, deine personenbezogenen Daten zu schützen?",
            },
            "uscomfort-01": {
                q:
                    "Alle oben erwähnten Firmen haben ihren Sitz in Amerika. Wie wohl fühlst du dich damit?",
            },
            "trust-05": {
                q:
                    "Wie sehr vertraust du einer Behörde, deine personenbezogenen Daten zu schützen?",
            },
            "gdpr-01": {
                q:
                    "Die Europäische Union hat 2018 die Datenschutz-Grundverordnung (DSGVO) erlassen. Was macht diese Verordnung?",
                o01: "Sie regelt, wie Firmen persönliche Daten benutzen dürfen.",
                o02: "Sie schützt Firmen im Fall von Datenverlust davor, verklagt zu werden.",
                o03: "Sie schützt Firmen vor Hackern.",
                o04:
                    "Sie schützt Hacker vor Strafverfolgung, wenn ihre Handlungen ein potentielles Datenrisiko offenlegen.",
                o05: "Sie stellt sicher, dass jeder den Cookies zustimmt.",
            },
            "gdpr-02": {
                q:
                    "Die DSGVO soll Personen mehr Kontrolle über ihre Daten geben. Sie gilt seit April 2018. Hast du seitdem den Eindruck, mehr oder weniger Kontrolle über deine personenbezogenen Daten zu haben?",
                o01: "Mehr Kontrolle",
                o02: "Weniger Kontrolle",
                o03: "Ungefähr gleich",
            },
            "control-13": {
                q: "Wer sollte verantwortlich dafür sein, wie Daten verwendet werden dürfen?",
                o01: "Meine Regierung",
                o02: "Die Europäische Union",
                o03: "Privatunternehmen",
                o04: "Die Menschen selbst",
            },
            "empowered-14": {
                q:
                    "Wie einflussreich fühlst du dich im Hinblick darauf, deine digitalen Rechte einzufordern?",
            },
            "affected-15": {
                q: "Warst du je von Datendiebstahl betroffen?",
                o03: "Nicht, dass ich wüsste",
            },
            "affected-16": { q: "Was für Probleme hat das für dich verursacht?" },
            "protected-17": {
                q:
                    "Mehr und mehr Menschen werden Opfer von Hackern und Datendiebstahl. Wie sicher fühlst du dich diesbezüglich?",
            },
            "priority-18": {
                q:
                    "Wenn es eine einfache Methode gäbe, die Kontrolle über deine Daten zurückzuerhalten - wärst du daran interessiert?",
                o03: "Nicht sicher",
                o04: "Ist mir egal",
            },
            "value-19": {
                q:
                    "Wenn du einschätzen solltest, wie wertoll deine Daten sind, welchen Wert würdest du ihnen geben?",
                o01: "Kein Ahnung",
                o02: "5€",
                o03: "50€",
                o04: "100€",
                o05: "Mehr",
            },
            "share-20": {
                q:
                    "Große Tech-Firmen machen Profit mit den Daten der Menschen, die ihre Dienste nutzen. Findest du, dass dir ein Anteil davon zusteht?",
                o01: "Ja - ich habe diese Daten erschaffen.",
                o02: "Nein - das ist das Resultat der Arbeit von anderen.",
                o03: "Ich bin mir nicht sicher.",
            },
            "access-21": {
                q: "Wer sollte Zugang zu deinen Daten besitzen?",
                o01: "Die Regierung",
                o02: "Dein Arbeitgeber",
                o03: "Strafverfolgungsbehörden",
                o04: "Gesundheitsämter",
                o05: "Finanzbehörden",
                o06: "Niemand ohne meine Erlaubnis.",
            },
            "TaCs-22": {
                q: "Wie oft liest du die Geschäftsbedingungen, bevor du zustimmst?",
                o01:
                    'Ich scrolle runter und klicke auf "Zustimmen". Sonst kann ich den Dienst nicht benutzen.',
                o02: 'Ich lese die Überschriften, bevor ich auf "Zustimmen" klicke.',
                o03:
                    'Ich lese alles durch und klicke auf "Zustimmen", selbst wenn ich mich mit dem Gelesenen nicht wohlfühle.',
                o04:
                    'Ich lese alles sorgfältig durch und denke darüber nach, bevor ich auf "Zustimmen" klicke.',
            },
            "familiar-23": {
                q: "Mit welchen der folgenden Begrifflichkeiten bist du vertraut?",
                o01: "Datensilo",
                o02: "Edge-Computing",
                o03: "Datenökonomie",
                o04: "Cookies",
                o05: "Maschinelles Lernen",
                o06: "Token",
                o07: "IP-Adresse",
                o08: "Hacken",
                o09: "Digitaler Innovationszyklus",
                o10: "API",
                o11: "Algorithmen",
            },
            "country-01": {
                q: "In welchem Land lebst du?",
                o01: "Belgien",
                o02: "Bulgarien",
                o03: "Dänemark",
                o04: "Deutschland",
                o05: "Estland",
                o06: "Finnland",
                o07: "Frankreich",
                o08: "Griechenland",
                o09: "Vereinigtes Königreich",
                o10: "Irland (Republik)",
                o11: "Italien",
                o12: "Kroatien",
                o13: "Lettland",
                o14: "Lithuania",
                o15: "Luxembourg",
                o16: "Malta",
                o17: "Niederlande",
                o18: "Österreich",
                o19: "Polen",
                o20: "Portugal",
                o21: "Rumänien",
                o22: "Schweden",
                o23: "Slowakei",
                o24: "Slowenien",
                o25: "Spanien",
                o26: "Tschechische Republik",
                o27: "Ungarn",
                o28: "Zypern",
                o29: "Anderes Land",
            },
        },
        en: {
            meta: {
                title: "Trust and the Data Economy",
                description:
                    "We want to better understand how much you trust the dataconomy and your understanding of your digital footprint. This will help us build a better polyPod in the future. Thank you!",
                legal: {
                    content:
                        "This survey is provided by polypoly GmbH, the makers of the polyPod. We do not collect any personal or private information. Only your response will be stored. No data from your device, how you use the app, or you will be collected. Lean more about the polyPod here:\n\n<1>https://pod.polypoly.eu</1>",
                    link: "https://pod.polypoly.eu",
                },
                author: {
                    name: "polypoly",
                    link: "https://polypoly.eu/en/home",
                    description:
                        "We’re the makers of the polyPod, a digital ecosystem that helps people take control back over their data. We want to make products that benefit you and return the power of data back to Europe.\n\nWe value Privacy by Design, digital pluralism, and the individual.\n\nFollow us on Twitter @polypolyEU for more about those things.",
                },
            },
            "usage-01": {
                q: "How would you describe your internet usage?",
                o01: "I use it primarily to communicate at work.",
                o02: "I use it to conduct my day-to-day work at the office.",
                o03: "I use it to conduct my day-to-day work and for personal socialization.",
                o04:
                    "I use it to conduct my day-to-day work as well as use it to socialize and some shopping.",
                o05: "I use the Internet for work, socialization, shopping, and for entertainment.",
            },
            "companies-01": {
                q: "Which of the following companies services and sites do you use for work?",
                o01: "Google",
                o02: "Facebook (including Instagram and WhatsApp)",
                o03: "Amazon",
                o04: "Apple",
                o05: "Microsoft",
                o06: "Twitter",
            },
            "companies-02": {
                q: "Which of the following companies services and sites do you use personally?",
                o01: "Google",
                o02: "Facebook (including Instagram and WhatsApp)",
                o03: "Amazon",
                o04: "Apple",
                o05: "Microsoft",
                o06: "Twitter",
            },
            "shopping-01": {
                q: "How much of your shopping do you do online?",
                o01: "None",
                o02: "Some",
                o03: "More than half",
                o04: "Almost all of it",
            },
            "trust-01": { q: "How much do you trust Facebook to keep your personal data secure?" },
            "trust-02": { q: "How much do you trust Google to keep your personal data secure?" },
            "trust-03": { q: "How much do you trust Apple to keep your personal data secure?" },
            "trust-04": { q: "How much do you trust Amazon to keep your personal data secure?" },
            "uscomfort-01": {
                q:
                    "The previously named companies are all based out of the United States of America. How comfortable are you with that?",
            },
            "trust-05": {
                q:
                    "How much do you trust a government institution to keep your personal data secure?",
            },
            "gdpr-01": {
                q:
                    "In 2018, the European Union put the General Data Protection Regulation. What does this law do?",
                o01: "Regulates how companies can use individual's data.",
                o02: "Protects companies from lawsuits in case of data breech.",
                o03: "Protects companies from hackers.",
                o04:
                    "Protects hackers from legal action if their actions expose a potential security risk.",
                o05: "Ensures that everyone agrees to cookies.",
            },
            "gdpr-02": {
                q:
                    "The GDPR is designed to give individuals more control over their personal data. Do you feel that you have more or less control over your personal data since it came into effect in April 2018?",
                o01: "More control",
                o02: "Less control",
                o03: "About the same",
            },
            "control-13": {
                q: "Who should be responsible for regulating the use of data?",
                o01: "My country's government",
                o02: "The European Union",
                o03: "Private corporations",
                o04: "Individuals themselves",
            },
            "empowered-14": {
                q:
                    "How empowered do you consider yourself when it comes to exercising your digital rights?",
            },
            "affected-15": {
                q: "Have you ever been affected by a data breach?",
                o03: "Not that I know of",
            },
            "affected-16": { q: "How did it affect you?" },
            "protected-17": {
                q:
                    "People are being increasingly targeted by hacks and data breaches. How protected do you feel?",
            },
            "priority-18": {
                q:
                    "If it were simple and required little effort, would you be interested in regaining control of your data?",
                o03: "Not sure",
                o04: "I don't care",
            },
            "value-19": {
                q: "How much do you believe your data is currently worth?",
                o01: "No idea",
                o02: "€5",
                o03: "€50",
                o04: "€100",
                o05: "More",
            },
            "share-20": {
                q:
                    "Large tech companies profit from the data that is created from people using their services. Do you feel entitled to a percentage of that profit?",
                o01: "Yes – I created that data.",
                o02: "No – it's the result of someone else's work.",
                o03: "Not sure.",
            },
            "access-21": {
                q: "Who should have access to your data?",
                o01: "Government",
                o02: "Employers",
                o03: "Law enforcement officials",
                o04: "Health officials",
                o05: "Financial institutions",
                o06: "No one without my persmission",
            },
            "TaCs-22": {
                q: "How often do you read the terms and conditions before agreeing to them?",
                o01:
                    'I scroll down and click "agree". I know this needs to happen if I want to use the service',
                o02: 'I read the headlines before clicking "agree".',
                o03:
                    "I read through everything and click \"agree\" even if I'm not comfortable with what I've read.",
                o04:
                    "I read through everything and thoughtfully consider agreeing before doing so.",
            },
            "familiar-23": {
                q: "Which of the following terms are you familiar with?",
                o01: "Data silo",
                o02: "Edge computing",
                o03: "Dataconomy",
                o04: "Cookies",
                o05: "Machine Learning",
                o06: "Token",
                o07: "IP address",
                o08: "Hacking",
                o09: "Digital innovation cycle",
                o10: "API",
                o11: "Algorithms",
            },
            "country-01": {
                q: "In which country do you live?",
                o01: "Belgium",
                o02: "Bulgaria",
                o03: "Denmark",
                o04: "Germany",
                o05: "Estonia",
                o06: "Finland",
                o07: "France",
                o08: "Greece",
                o09: "United Kingdom",
                o10: "Ireland (Republic)",
                o11: "Italy",
                o12: "Croatia",
                o13: "Latvia",
                o14: "Lithuania",
                o15: "Luxemburg",
                o16: "Malta",
                o17: "Netherlands",
                o18: "Austria",
                o19: "Poland",
                o20: "Portugal",
                o21: "Romania",
                o22: "Sweden",
                o23: "Slovakia",
                o24: "Slovenia",
                o25: "Spain",
                o26: "Czech Republic",
                o27: "Hungary",
                o28: "Cyprus",
                o29: "Other",
            },
        },
    },
};
