[workspace]
members = ["lib", "ffi", "crates/*"]

[profile.dev]
# Disabling debug info speeds up builds a bunch,
# If you want to be able to debug core, then consider incresing this value appropriately.
debug = 0
