export default {
    ppid: "APPLE INC.",
    name: "%%APPLE INC.",
    featured: true,
    jurisdiction: "Five-Eyes",
    location: {
        city: "Cupertino",
        countryCode: "US",
    },
    annualRevenues: [],
    dataRecipients: [
        "Accenture (IE)",
        "American Heart Association (US)",
        "Cisco Systems Inc (US)",
        "Deloitte (GB)",
        "Deloitte (LU)",
        "Deloitte Consulting Inc. (US)",
        "Deloitte Consulting Inc.(US)",
        "Deloitte Tax LLP (US)",
        "Department of Medicine at Brigham and Women’s Hospital (US)",
        "Green Dot Bank (US)",
        "Green Dot Corporation (US)",
        "Harvard T H Chan School (US )",
        "IBM (US)",
        "NIEHS (US)",
        "SAP (DE)",
        "Salesforce, Inc. (US)",
        "University Of Michigan (US)",
        "d/b/a GoBank (US)",
        "salesforce.com, Inc. (US)",
    ],
    dataSharingPurposes: [
        {
            "dpv:Purpose": "dpv:AcademicResearch",
            count: 91,
            Translation_DE: "Akademische Forschung",
            Translation_EN: "Academic Research",
            Explanation_DE:
                "Forschung in einem akademischen Kontext, z. B. durch die Durchführung oder Unterstützung von Universitäten.",
            Explanation_EN:
                "Conduct or assist with research conducted in an academic context e.g. within universities.",
        },
        {
            "dpv:Purpose": "dpv:Advertising",
            count: 2,
            Translation_DE: "Werbung",
            Translation_EN: "Advertising",
            Explanation_DE: "Werbung und werbliche Ansprache.",
            Explanation_EN: "Advertising and sending messages with ad content.",
        },
        {
            "dpv:Purpose": "dpv:CommercialInterest",
            count: 66,
            Translation_DE: "Kommerzielles Interesse",
            Translation_EN: "Commercial Interest",
            Explanation_DE:
                "Aktivitäten mit einem kommerziellen Interesse durchführen, d. h. mit Gewinn oder Nutzen für die Prüfenden.",
            Explanation_EN:
                "Carry out activities with a commercial interest i.e. of profit or benefit to the Controller.",
        },
        {
            "dpv:Purpose": "dpv:CommercialResearch",
            count: 20,
            Translation_DE: "Kommerzielle Forschung",
            Translation_EN: "Commercial Research",
            Explanation_DE:
                "Forschung in einem kommerziellen Umfeld betreiben, z. B. in einem Unternehmen.",
            Explanation_EN:
                "Conduct research in a commercial setting e.g. in a company.",
        },
        {
            "dpv:Purpose": "dpv:CommunicationForCustomerCare",
            count: 5,
            Translation_DE: "Kommunikation zur Kund:innen-Betreuung",
            Translation_EN: "Communication for Customer Care",
            Explanation_DE:
                "Mit Nutzer:innen per E-Mail, Telefon, SMS, Chat oder Push-Nachrichten über Ihre Anfragen kommunizieren.",
            Explanation_EN:
                "Communicate with users via email, phone, sms, chat or push messages regarding your requests.",
        },
        {
            "dpv:Purpose": "dpv:CreatePersonalizedRecommendations",
            count: 1,
            Translation_DE: "Personalisierte Empfehlungen erstellen",
            Translation_EN: "Create Personalized Recommendations",
            Explanation_DE:
                "Personalisierte Empfehlungen erstellen und bereitstellen.",
            Explanation_EN: "Create and provide personalised recommendations.",
        },
        {
            "dpv:Purpose": "dpv:CustomerCare",
            count: 23,
            Translation_DE: "Kund:innen-Betreuung",
            Translation_EN: "Customer Care",
            Explanation_DE:
                "Hilfestellung bei Kund:innen-Beschwerden und -Zufriedenheit geben.",
            Explanation_EN:
                "Provide assistance for customer complaints and satisfaction.",
        },
        {
            "dpv:Purpose": "dpv:DeliveryOfGoods",
            count: 1,
            Translation_DE: "Lieferung von Waren",
            Translation_EN: "Delivery of Goods",
            Explanation_DE: "Waren und Dienstleistungen ausliefern.",
            Explanation_EN: "Deliver goods and services.",
        },
        {
            "dpv:Purpose": "dpv:DirectMarketing",
            count: 4,
            Translation_DE: "Direktmarketing",
            Translation_EN: "Direct marketing",
            Explanation_DE:
                "Direktmarketing durchführen, d.h. gezieltes Marketing, das direkt an eine individuelle Person gerichtet ist.",
            Explanation_EN:
                "Carry out direct marketing i.e. marketing communicated directly to the individual.",
        },
        {
            "dpv:Purpose": "dpv:FraudPreventionAndDetection",
            count: 9,
            Translation_DE: "Betrugsprävention und -aufdeckung",
            Translation_EN: "Fraud Prevention and Detection",
            Explanation_DE: "Betrug erkennen und verhindern.",
            Explanation_EN: "Detect and prevent fraud.",
        },
        {
            "dpv:Purpose": "dpv:IdentityVerification",
            count: 1,
            Translation_DE: "Identitätsüberprüfung",
            Translation_EN: "Identity Verification",
            Explanation_DE: "Identität verifizieren und autorisieren.",
            Explanation_EN: "Verify and authorise identity.",
        },
        {
            "dpv:Purpose": "dpv:ImproveExistingProductsAndServices",
            count: 107,
            Translation_DE:
                "Bestehende Produkte und Dienstleistungen verbessern",
            Translation_EN: "Improve Existing Products and Services",
            Explanation_DE:
                "Bestehende Produkte und Dienstleistungen verbessern.",
            Explanation_EN: "Improve existing products and services.",
        },
        {
            "dpv:Purpose": "dpv:InternalResourceOptimisation",
            count: 17,
            Translation_DE: "Interne Ressourcen-Optimierung",
            Translation_EN: "Internal Resource Optimisation",
            Explanation_DE:
                "Optimierung interner Ressourcen, die von der Organisation genutzt werden, z. B. die Ressourcennutzung.",
            Explanation_EN:
                "Optimise activities and services for the Controller, meaning the company that controls the data handling.",
        },
        {
            "dpv:Purpose": "dpv:LegalCompliance",
            count: 82,
            Translation_DE: "Rechtskonformität",
            Translation_EN: "Legal Compliance",
            Explanation_DE:
                "Verpflichtungen oder Anforderungen erfüllen, um die Einhaltung von Gesetzen oder Vorschriften zu gewährleisten.",
            Explanation_EN:
                "Fulfil obligations or requirements towards achieving compliance with law or regulations.",
        },
        {
            "dpv:Purpose": "dpv:Marketing",
            count: 6,
            Translation_DE: "Marketing",
            Translation_EN: "Marketing",
            Explanation_DE:
                "Marketing betreiben, d. h. ein Produkt oder eine Dienstleistung bewerben, verkaufen und vertreiben.",
            Explanation_EN:
                "Carry out marketing i.e. promoting, selling, and distributing a product or service.",
        },
        {
            "dpv:Purpose": "dpv:NonCommercialResearch",
            count: 18,
            Translation_DE: "Nicht-kommerzielle Forschung",
            Translation_EN: "Non-Commercial Research",
            Explanation_DE:
                "Forschung in einem nicht-kommerziellen Umfeld betreiben, z. B. für eine Non-Profit-Organisation (NGO).",
            Explanation_EN:
                "Conduct research in a non-commercial setting e.g. for a non-profit-organisation (NGO).",
        },
        {
            "dpv:Purpose": "dpv:OptimisationForController",
            count: 20,
            Translation_DE: "Optimierung für Kontrolleur:innen",
            Translation_EN: "Optimisation for Controller",
            Explanation_DE:
                "Optimierung von Aktivitäten und Diensten für Datenverantwortliche, also für die Firma, die die Daten kontrolliert.",
            Explanation_EN:
                "Optimise activities and services for the Controller.",
        },
        {
            "dpv:Purpose": "dpv:Payment",
            count: 8,
            Translation_DE: "Bezahlung",
            Translation_EN: "Payment",
            Explanation_DE:
                "Die Zahlungstransaktionen der Nutzer:innen verarbeiten.",
            Explanation_EN: "Process users’ payment transactions.",
        },
        {
            "dpv:Purpose": "dpv:PersonalisedBenefits",
            count: 3,
            Translation_DE: "Personalisierte Vorteile",
            Translation_EN: "Personalised Benefits",
            Explanation_DE:
                "Die von den Nutzenden erhaltenen Leistungen personalisieren.",
            Explanation_EN: "Personalise benefits received by the user.",
        },
        {
            "dpv:Purpose": "dpv:RegistrationAuthentication",
            count: 1,
            Translation_DE: "Registrierung und Authentifizierung",
            Translation_EN: "Registration and Authentication",
            Explanation_DE:
                "Registrierung, Authentifizierung und Identifizierung im Kontext eines Dienstes.",
            Explanation_EN:
                "Register, authenticate, and identify in context of a service.",
        },
        {
            "dpv:Purpose": "dpv:ResearchAndDevelopment",
            count: 7,
            Translation_DE: "Forschung und Entwicklung",
            Translation_EN: "Research and Development",
            Explanation_DE:
                "Forschung und Entwicklung für neue Methoden, Produkte oder Dienstleistungen betreiben.",
            Explanation_EN:
                "Conduct research and development for new methods, products, or services.",
        },
        {
            "dpv:Purpose": "dpv:Security",
            count: 39,
            Translation_DE: "Sicherheit",
            Translation_EN: "Security",
            Explanation_DE:
                "Die Sicherheit z. B. von Daten, gewährleisten und durchsetzen.",
            Explanation_EN: "Ensure and enforce security e.g. of data.",
        },
        {
            "dpv:Purpose": "dpv:ServiceOptimization",
            count: 2,
            Translation_DE: "Service-Optimierung",
            Translation_EN: "Service Optimization,",
            Explanation_DE: "Service oder Aktivität optimieren.",
            Explanation_EN: "Optimise service or activity.",
        },
        {
            "dpv:Purpose": "dpv:ServicePersonalization",
            count: 2,
            Translation_DE: "Dienstpersonalisierung",
            Translation_EN: "Service Personalization",
            Explanation_DE: "Dienstleistung oder Aktivität personalisieren.",
            Explanation_EN: "Personalise service or activity.",
        },
        {
            "dpv:Purpose": "dpv:ServiceProvision",
            count: 239,
            Translation_DE: "Dienstbereitstellung",
            Translation_EN: "Service Provision",
            Explanation_DE: "Dienstleistung oder Aktivität anbieten.",
            Explanation_EN: "Provide service or activity.",
        },
        {
            "dpv:Purpose": "dpv:UsageAnalytics",
            count: 20,
            Translation_DE: "Verwendungsanalyse",
            Translation_EN: "Usage Analytics",
            Explanation_DE:
                ",Berechnen, Analysieren und Berichten von Benutzer:innen-Verhalten und -Ereignissen für einen Dienst oder ein Produkt.",
            Explanation_EN:
                "Calculate, analyse, and report user behaviour and events for a service or product.",
        },
        {
            "dpv:Purpose": "dpv:UserInterfacePersonalisation",
            count: 1,
            Translation_DE: "Personalisierung der Benutzer:innen-Oberfläche",
            Translation_EN: "User Interface Personalisation",
            Explanation_DE:
                "Oberflächen für den:die Benutzer:in personalisieren.",
            Explanation_EN: "Personalise interfaces presented to the user.",
        },
        {
            "dpv:Purpose": "unspecified",
            count: 23,
            Translation_DE: "Unspezifiziert",
            Translation_EN: "Unspecified",
            Explanation_DE: "Zweck nicht spezifiziert.",
            Explanation_EN: "Purpose unspecified.",
        },
    ],
    dataTypesShared: [
        {
            "dpv:Category": "dpv:Accent",
            count: 34,
            "dpv:Superclass": "dpv:Language",
            Translation_DE: "Akzent",
            Translation_EN: "Accent",
            Polypoly_Parent_Category: ["pppc:IndividualData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen über einen Sprach- und Sprechakzent.",
            Explanation_EN:
                "Information about an linguistic and speech accents.",
        },
        {
            "dpv:Category": "dpv:AccountIdentifier",
            count: 3,
            "dpv:Superclass": "dpv:FinancialAccount",
            Translation_DE: "Konto-Identifikator",
            Translation_EN: "Account Identifier",
            Polypoly_Parent_Category: ["pppc:FinancialData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen über die Kennung eines Finanzkontos.",
            Explanation_EN: "Information about financial account identifier.",
        },
        {
            "dpv:Category": "dpv:Age",
            count: 39,
            "dpv:Superclass": "dpv:PhysicalCharacteristic",
            Translation_DE: "Alter",
            Translation_EN: "Age",
            Polypoly_Parent_Category: ["pppc:IndividualData"],
            Synonyms: "“Date Of Birth”;”DOB”;”DateOfBirth”",
            Explanation_DE: "Informationen über das Alter",
            Explanation_EN: "Information about age",
        },
        {
            "dpv:Category": "dpv:Authenticating",
            count: 35,
            "dpv:Superclass": "dpv:Internal",
            Translation_DE: "Authentifizierung",
            Translation_EN: "Authenticating",
            Polypoly_Parent_Category: ["pppc:TechnicalData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen über die Authentifizierung und die zur Authentifizierung verwendeten Informationen",
            Explanation_EN:
                "Information about authentication and information used for authenticating",
        },
        {
            "dpv:Category": "dpv:Behavioral",
            count: 3,
            "dpv:Superclass": "dpv:External",
            Translation_DE: "Verhaltensweisen",
            Translation_EN: "Behavioral",
            Polypoly_Parent_Category: ["pppc:BehavioralData"],
            Synonyms: "",
            Explanation_DE: "Informationen über Verhalten oder Aktivität",
            Explanation_EN: "Information about behavior or activity",
        },
        {
            "dpv:Category": "dpv:BrowserFingerprint",
            count: 1,
            "dpv:Superclass": "dpv:DeviceBased",
            Translation_DE: "Browser-Fingerabdruck",
            Translation_EN: "Browser Fingerprint",
            Polypoly_Parent_Category: ["pppc:TechnicalData"],
            Synonyms: "",
            Explanation_DE:
                'Informationen über den Webbrowser, der als "Fingerabdruck" verwendet wird',
            Explanation_EN:
                "Information about the web browser which is used as a 'fingerprint'",
        },
        {
            "dpv:Category": "dpv:BrowsingBehavior",
            count: 12,
            "dpv:Superclass": "dpv:Behavioral",
            Translation_DE: "Browsing-Verhalten",
            Translation_EN: "Browsing Behavior",
            Polypoly_Parent_Category: ["pppc:BehavioralData"],
            Synonyms: "",
            Explanation_DE: "Informationen über das Browsing-Verhalten.",
            Explanation_EN: "Information about browsing behaviour.",
        },
        {
            "dpv:Category": "dpv:BrowsingReferral",
            count: 1,
            "dpv:Superclass": "dpv:BrowsingBehavior",
            Translation_DE: "Browsing-Empfehlung",
            Translation_EN: "Browsing Referral",
            Polypoly_Parent_Category: ["pppc:BehavioralData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen über Web-Browsing Referrer oder Verweise, die auf Standort, gezielten Verweisen, direkter, organischer Suche, sozialen Medien oder Aktionen, Kampagnen basieren können.",
            Explanation_EN:
                "Information about web browsing referrer or referral, which can be based on location, targeted referrals, direct, organic search, social media or actions, campaigns.",
        },
        {
            "dpv:Category": "dpv:Communication",
            count: 4,
            "dpv:Superclass": "dpv:Social",
            Translation_DE: "Kommunikation",
            Translation_EN: "Communication",
            Polypoly_Parent_Category: ["pppc:SocialData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen, die von oder an eine Person kommuniziert wurden",
            Explanation_EN: "Information communicated from or to an individual",
        },
        {
            "dpv:Category": "dpv:Country",
            count: 8,
            "dpv:Superclass": "dpv:Location",
            Translation_DE: "Land",
            Translation_EN: "Country",
            Polypoly_Parent_Category: ["pppc:IndividualData"],
            Synonyms: "",
            Explanation_DE: "Informationen über das Land z.B. Wohnsitz, Reise.",
            Explanation_EN: "Information about country e.g. residence, travel.",
        },
        {
            "dpv:Category": "dpv:CreditRecord",
            count: 2,
            "dpv:Superclass": "dpv:Credit",
            Translation_DE: "Kreditrekord",
            Translation_EN: "Credit Record",
            Polypoly_Parent_Category: ["pppc:FinancialData"],
            Synonyms: "",
            Explanation_DE: "Informationen über die Kreditwürdigkeit.",
            Explanation_EN: "Information about credit record.",
        },
        {
            "dpv:Category": "dpv:Demographic",
            count: 1,
            "dpv:Superclass": "dpv:External",
            Translation_DE: "Demografische Daten",
            Translation_EN: "Demographic",
            Polypoly_Parent_Category: ["pppc:SocialData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen über Demografie und demografische Merkmale",
            Explanation_EN:
                "Information about demography and demographic characteristics",
        },
        {
            "dpv:Category": "dpv:DeviceApplications",
            count: 2,
            "dpv:Superclass": "dpv:DeviceSoftware",
            Translation_DE: "Geräteanwendungen",
            Translation_EN: "Device Applications",
            Polypoly_Parent_Category: ["pppc:TechnicalData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen über Anwendungen oder anwendungsähnliche Software auf einem Gerät.",
            Explanation_EN:
                "Information about applications or application-like software on a device.",
        },
        {
            "dpv:Category": "dpv:DeviceBased",
            count: 17,
            "dpv:Superclass": "dpv:Tracking",
            Translation_DE: "Gerätebasiert",
            Translation_EN: "Device Based",
            Polypoly_Parent_Category: ["pppc:TechnicalData"],
            Synonyms: "",
            Explanation_DE: "Informationen über Geräte",
            Explanation_EN: "Information about devices",
        },
        {
            "dpv:Category": "dpv:DeviceOperatingSystem",
            count: 2,
            "dpv:Superclass": "dpv:DeviceSoftware",
            Translation_DE: "Geräte-Betriebssystem",
            Translation_EN: "Device Operating System",
            Polypoly_Parent_Category: ["pppc:TechnicalData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen über das Betriebssystem (OS) oder die Systemsoftware, die Hardware- oder Softwareressourcen verwaltet.",
            Explanation_EN:
                "Information about the operating system (OS) or system software that manages hardware or software resources.",
        },
        {
            "dpv:Category": "dpv:DeviceSoftware",
            count: 2,
            "dpv:Superclass": "dpv:DeviceBased",
            Translation_DE: "Geräte-Software",
            Translation_EN: "Device Software",
            Polypoly_Parent_Category: ["pppc:TechnicalData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen über Software auf einem Gerät oder im Zusammenhang mit einem Gerät.",
            Explanation_EN:
                "Information about software on or related to a device.",
        },
        {
            "dpv:Category": "dpv:Dialect",
            count: 34,
            "dpv:Superclass": "dpv:Language",
            Translation_DE: "Dialekt",
            Translation_EN: "Dialect",
            Polypoly_Parent_Category: ["pppc:IndividualData"],
            Synonyms: "",
            Explanation_DE: "Informationen zu sprachlichen Dialekten.",
            Explanation_EN: "Information about linguistic dialects.",
        },
        {
            "dpv:Category": "dpv:EmailAddress",
            count: 43,
            "dpv:Superclass": "dpv:Contact",
            Translation_DE: "E-Mail Adresse",
            Translation_EN: "Email Address",
            Polypoly_Parent_Category: [
                "pppc:IndividualData",
                "pppcTechnicalData",
            ],
            Synonyms: "",
            Explanation_DE: "Informationen über E-Mail-Adressen.",
            Explanation_EN: "Information about Email address.",
        },
        {
            "dpv:Category": "dpv:EthnicOrigin",
            count: 1,
            "dpv:Superclass": "dpv:Ethnicity;dpv:SpecialCategoryPersonalData",
            Translation_DE: "Ethnische Herkunft",
            Translation_EN: "Ethnic Origin",
            Polypoly_Parent_Category: ["pppc:IndividualData"],
            Synonyms: "",
            Explanation_DE: "Informationen über die ethnische Herkunft",
            Explanation_EN: "Information about ethnic origin",
        },
        {
            "dpv:Category": "dpv:Financial",
            count: 41,
            "dpv:Superclass": "dpv:PersonalDataCategory",
            Translation_DE: "Finanzen",
            Translation_EN: "Financial",
            Polypoly_Parent_Category: ["pppc:FinancialData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen über Finanzen einschließlich monetärer Merkmale und Transaktionen",
            Explanation_EN:
                "Information about finance including monetary characteristics and transactions",
        },
        {
            "dpv:Category": "dpv:FinancialAccount",
            count: 1,
            "dpv:Superclass": "dpv:Financial",
            Translation_DE: "Finanzkonto",
            Translation_EN: "Financial Account",
            Polypoly_Parent_Category: ["pppc:FinancialData"],
            Synonyms: "",
            Explanation_DE: "Informationen über Finanzkonten.",
            Explanation_EN: "Information about financial accounts.",
        },
        {
            "dpv:Category": "dpv:GPSCoordinate",
            count: 1,
            "dpv:Superclass": "dpv:Location",
            Translation_DE: "GPS-Koordinate",
            Translation_EN: "GPS Coordinate",
            Polypoly_Parent_Category: ["pppc:TechnicalData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen über den Standort, ausgedrückt durch Global Position System-Koordinaten (GPS)",
            Explanation_EN:
                "Information about location expressed using Global Position System coordinates (GPS)",
        },
        {
            "dpv:Category": "dpv:Gender",
            count: 1,
            "dpv:Superclass": "dpv:PhysicalCharacteristic",
            Translation_DE: "Geschlecht",
            Translation_EN: "Gender",
            Polypoly_Parent_Category: ["pppc:IndividualData"],
            Synonyms: "",
            Explanation_DE: "Informationen über das Geschlecht",
            Explanation_EN: "Information about gender",
        },
        {
            "dpv:Category": "dpv:Geographic",
            count: 2,
            "dpv:Superclass": "dpv:Demographic",
            Translation_DE: "Geografisch",
            Translation_EN: "Geographic",
            Polypoly_Parent_Category: ["pppc:IndividualData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen über den Standort oder basierend auf der Geografie (z. B. die Heimatadresse)",
            Explanation_EN:
                "Information about location or based on geography (e.g., home address)",
        },
        {
            "dpv:Category": "dpv:Health",
            count: 45,
            "dpv:Superclass": "dpv:MedicalHealth",
            Translation_DE: "Gesundheit",
            Translation_EN: "Health",
            Polypoly_Parent_Category: ["pppc:IndividualData"],
            Synonyms: "",
            Explanation_DE: "Informationen über die Gesundheit.",
            Explanation_EN: "Information about health.",
        },
        {
            "dpv:Category": "dpv:HealthHistory",
            count: 1,
            "dpv:Superclass": "dpv:MedicalHealth",
            Translation_DE: "Gesundheit Geschichte",
            Translation_EN: "Health History",
            Polypoly_Parent_Category: ["pppc:IndividualData"],
            Synonyms: "",
            Explanation_DE: "Informationen über die Gesundheitshistorie.",
            Explanation_EN: "Information about health history.",
        },
        {
            "dpv:Category": "dpv:HealthRecord",
            count: 1,
            "dpv:Superclass": "dpv:MedicalHealth",
            Translation_DE: "Gesundheitsakte",
            Translation_EN: "Health Record",
            Polypoly_Parent_Category: ["pppc:IndividualData"],
            Synonyms: "",
            Explanation_DE: "Informationen über die Gesundheitsakte.",
            Explanation_EN: "Information about health record.",
        },
        {
            "dpv:Category": "dpv:IPAddress",
            count: 2,
            "dpv:Superclass": "dpv:DeviceBased",
            Translation_DE: "IP-Adresse",
            Translation_EN: "IP Address",
            Polypoly_Parent_Category: ["pppc:TechnicalData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen über die Internetprotokoll (IP)-Adresse eines Geräts",
            Explanation_EN:
                "Information about the Internet protocol (IP) address of a device",
        },
        {
            "dpv:Category": "dpv:Identifying",
            count: 34,
            "dpv:Superclass": "dpv:External",
            Translation_DE: "Identifizieren",
            Translation_EN: "Identifying",
            Polypoly_Parent_Category: ["pppc:IndividualData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen, die eine Einzelperson oder eine Gruppe eindeutig oder halbeindeutig identifizieren",
            Explanation_EN:
                "Information that uniquely or semi-uniquely identifies an individual or a group",
        },
        {
            "dpv:Category": "dpv:Income",
            count: 34,
            "dpv:Superclass": "dpv:Transactional",
            Translation_DE: "Einkommen",
            Translation_EN: "Income",
            Polypoly_Parent_Category: ["pppc:FinancialData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen über finanzielles Einkommen z.B. für Einzelperson oder Haushalt oder Familie",
            Explanation_EN:
                "Information about financial income e.g. for individual or household or family",
        },
        {
            "dpv:Category": "dpv:IndividualHealthHistory",
            count: 1,
            "dpv:Superclass": "dpv:HealthHistory",
            Translation_DE: "Individuelle Gesundheitsgeschichte",
            Translation_EN: "Individual Health History",
            Polypoly_Parent_Category: ["pppc:IndividualData"],
            Synonyms: "",
            Explanation_DE: "Informationen über die Gesundheitshistorie.",
            Explanation_EN: "Information about information health history.",
        },
        {
            "dpv:Category": "dpv:Interest",
            count: 7,
            "dpv:Superclass": "dpv:Preference",
            Translation_DE: "Interesse",
            Translation_EN: "Interest",
            Polypoly_Parent_Category: ["pppc:SocialData"],
            Synonyms: "",
            Explanation_DE: "Informationen über Interessen",
            Explanation_EN: "Information about interests",
        },
        {
            "dpv:Category": "dpv:Internal",
            count: 2,
            "dpv:Superclass": "dpv:PersonalDataCategory",
            Translation_DE: "Intern",
            Translation_EN: "Internal",
            Polypoly_Parent_Category: ["pppc:IndividualData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen über interne Merkmale, die nicht gesehen oder beobachtet werden können",
            Explanation_EN:
                "Information about internal characteristics that cannot be seen or observed",
        },
        {
            "dpv:Category": "dpv:Language",
            count: 34,
            "dpv:Superclass": "dpv:Ethnicity",
            Translation_DE: "Sprache",
            Translation_EN: "Language",
            Polypoly_Parent_Category: [
                "pppc:SocialData",
                "pppc:IndividualData",
            ],
            Synonyms: "",
            Explanation_DE: "Informationen über Sprache und Sprachgeschichte.",
            Explanation_EN: "Information about language and lingual history.",
        },
        {
            "dpv:Category": "dpv:LinkClicked",
            count: 3,
            "dpv:Superclass": "dpv:Behavioral",
            Translation_DE: "Linkgeklickt",
            Translation_EN: "LinkClicked",
            Polypoly_Parent_Category: ["pppc:BehavioralData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen über die Links, die eine Person angeklickt hat.",
            Explanation_EN:
                "Information about the links that an individual has clicked.",
        },
        {
            "dpv:Category": "dpv:Location",
            count: 2,
            "dpv:Superclass": "dpv:Tracking",
            Translation_DE: "Standort",
            Translation_EN: "Location",
            Polypoly_Parent_Category: ["pppc:IndividualData"],
            Synonyms: "",
            Explanation_DE: "Informationen über den Standort",
            Explanation_EN: "Information about location",
        },
        {
            "dpv:Category": "dpv:MedicalHealth",
            count: 35,
            "dpv:Superclass": "dpv:External;dpv:SpecialCategoryPersonalData",
            Translation_DE: "Medizinische Gesundheit",
            Translation_EN: "Medical Health",
            Polypoly_Parent_Category: ["pppc:IndividualData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen über Gesundheit, medizinische Bedingungen oder Gesundheitsvorsorge",
            Explanation_EN:
                "Information about health, medical conditions or health care",
        },
        {
            "dpv:Category": "dpv:MentalHealth",
            count: 34,
            "dpv:Superclass": "dpv:Health",
            Translation_DE: "Psychische Gesundheit",
            Translation_EN: "Mental Health",
            Polypoly_Parent_Category: ["pppc:IndividualData"],
            Synonyms: "",
            Explanation_DE: "Informationen über die psychische Gesundheit.",
            Explanation_EN: "Information about mental health.",
        },
        {
            "dpv:Category": "dpv:Name",
            count: 10,
            "dpv:Superclass": "dpv:Identifying",
            Translation_DE: "Name",
            Translation_EN: "Name",
            Polypoly_Parent_Category: ["pppc:IndividualData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen über Namen, die mit dem Gerät verbunden sind oder als Vornamen oder Spitznamen verwendet werden.",
            Explanation_EN:
                "Information about names associated or used as given name or nickname.",
        },
        {
            "dpv:Category": "dpv:OfficialID",
            count: 2,
            "dpv:Superclass": "dpv:Identifying",
            Translation_DE: "Offizieller Ausweis",
            Translation_EN: "Official ID",
            Polypoly_Parent_Category: ["pppc:IndividualData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen über eine offizielle Kennung oder ein Ausweisdokument",
            Explanation_EN:
                "Information about an official identifier or identification document",
        },
        {
            "dpv:Category": "dpv:Offspring",
            count: 1,
            "dpv:Superclass": "dpv:FamilyStructure",
            Translation_DE: "Nachkommenschaft",
            Translation_EN: "Offspring",
            Polypoly_Parent_Category: ["pppc:SocialData"],
            Synonyms: "",
            Explanation_DE: "Informationen über Nachkommenschaft(en).",
            Explanation_EN: "Information about offspring(s).",
        },
        {
            "dpv:Category": "dpv:Ownership",
            count: 34,
            "dpv:Superclass": "dpv:Financial",
            Translation_DE: "Eigentum",
            Translation_EN: "Ownership",
            Polypoly_Parent_Category: ["pppc:FinancialData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen über Besitz und Geschichte, einschließlich Mieten, Leihen, Besitztümer.",
            Explanation_EN:
                "Information about ownership and history, including renting, borrowing, possessions.",
        },
        {
            "dpv:Category": "dpv:PINCode",
            count: 1,
            "dpv:Superclass": "dpv:Authenticating",
            Translation_DE: "PIN-Code",
            Translation_EN: "PIN Code",
            Polypoly_Parent_Category: ["pppc:TechnicalData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen über die persönliche Identifikationsnummer (PIN), die üblicherweise bei der Authentifizierung der Person als Benutzer beim Zugriff auf ein System verwendet wird.",
            Explanation_EN:
                "Information about Personal identification number (PIN), which is usually used in the process of authenticating the individual as a user accessing a system.",
        },
        {
            "dpv:Category": "dpv:Password",
            count: 14,
            "dpv:Superclass": "dpv:Authenticating",
            Translation_DE: "Passwort",
            Translation_EN: "Password",
            Polypoly_Parent_Category: [
                "pppc:IndividualData",
                "pppc:TechnicalData",
            ],
            Synonyms: "",
            Explanation_DE:
                "Informationen über ein Passwort, das bei der Authentifizierung der Person als Benutzer beim Zugriff auf ein System verwendet wird.",
            Explanation_EN:
                "Information about password used in the process of authenticating the individual as a user accessing a system.",
        },
        {
            "dpv:Category": "dpv:PaymentCard",
            count: 1,
            "dpv:Superclass": "dpv:FinancialAccount",
            Translation_DE: "Zahlungskarte",
            Translation_EN: "Payment Card",
            Polypoly_Parent_Category: ["pppc:FinancialData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen über die Zahlungskarte, wie z. B. Kreditkarte, Debitkarte.",
            Explanation_EN:
                "Information about payment card such as Credit Card, Debit Card.",
        },
        {
            "dpv:Category": "dpv:PhysicalAddress",
            count: 3,
            "dpv:Superclass": "dpv:Contact",
            Translation_DE: "Physikalische Adresse",
            Translation_EN: "Physical Address",
            Polypoly_Parent_Category: ["pppc:IndividualData"],
            Synonyms: "",
            Explanation_DE: "Informationen über die physische Adresse.",
            Explanation_EN: "Information about physical address.",
        },
        {
            "dpv:Category": "dpv:PhysicalHealth",
            count: 36,
            "dpv:Superclass": "dpv:Health",
            Translation_DE: "Körperliche Gesundheit",
            Translation_EN: "Physical Health",
            Polypoly_Parent_Category: ["pppc:IndividualData"],
            Synonyms: "",
            Explanation_DE: "Informationen über die körperliche Gesundheit.",
            Explanation_EN: "Information about physical health.",
        },
        {
            "dpv:Category": "dpv:Picture",
            count: 36,
            "dpv:Superclass": "dpv:Identifying",
            Translation_DE: "Bild",
            Translation_EN: "Picture",
            Polypoly_Parent_Category: ["pppc:IndividualData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen über die visuelle Darstellung oder das Image, z. B. ein Profilfoto.",
            Explanation_EN:
                "Information about visual representation or image e.g. profile photo.",
        },
        {
            "dpv:Category": "dpv:PrivacyPreference",
            count: 3,
            "dpv:Superclass": "dpv:Preference",
            Translation_DE: "Datenschutz-Präferenz",
            Translation_EN: "Privacy Preference",
            Polypoly_Parent_Category: ["pppc:IndividualData"],
            Synonyms: "",
            Explanation_DE: "Informationen über Datenschutzpräferenzen",
            Explanation_EN: "Information about privacy preferences",
        },
        {
            "dpv:Category": "dpv:Purchase",
            count: 4,
            "dpv:Superclass": "dpv:Transactional",
            Translation_DE: "Einkaufen",
            Translation_EN: "Purchase",
            Polypoly_Parent_Category: ["pppc:FinancialData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen über Einkäufe wie z. B. gekaufte Lebensmittel oder Kleidung",
            Explanation_EN:
                "Information about purchases such as items bought e.g. grocery or clothing",
        },
        {
            "dpv:Category": "dpv:Salary",
            count: 34,
            "dpv:Superclass": "dpv:Professional",
            Translation_DE: "Gehalt",
            Translation_EN: "Salary",
            Polypoly_Parent_Category: ["pppc:FinancialData"],
            Synonyms: "",
            Explanation_DE: "Informationen über das Gehalt",
            Explanation_EN: "Information about salary",
        },
        {
            "dpv:Category": "dpv:SecretText",
            count: 6,
            "dpv:Superclass": "dpv:Authenticating",
            Translation_DE: "Geheimtext",
            Translation_EN: "Secret Text",
            Polypoly_Parent_Category: ["pppc:TechnicalData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen über geheimen Text, der im Prozess der Authentifizierung der Person als Benutzer beim Zugriff auf ein System verwendet wird, z. B. bei der Wiederherstellung eines verlorenen Passworts.",
            Explanation_EN:
                "Information about secret text used in the process of authenticating the individual as a user accessing a system, e.g., when recovering a lost password.",
        },
        {
            "dpv:Category": "dpv:TelephoneNumber",
            count: 10,
            "dpv:Superclass": "dpv:Contact",
            Translation_DE: "Telefon-Nummer",
            Translation_EN: "Telephone Number",
            Polypoly_Parent_Category: [
                "pppc:IndividualData",
                "pppcTechnicalData",
            ],
            Synonyms: "",
            Explanation_DE: "Informationen über Telefonnummern.",
            Explanation_EN: "Information about telephone number.",
        },
        {
            "dpv:Category": "dpv:Transaction",
            count: 1,
            "dpv:Superclass": "dpv:Transactional",
            Translation_DE: "Transaktion",
            Translation_EN: "Transaction",
            Polypoly_Parent_Category: ["pppc:FinancialData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen über finanzielle Transaktionen z.B. Banküberweisungen",
            Explanation_EN:
                "Information about financial transactions e.g. bank transfers",
        },
        {
            "dpv:Category": "dpv:Transactional",
            count: 7,
            "dpv:Superclass": "dpv:Financial",
            Translation_DE: "Transaktionsbezogen",
            Translation_EN: "Transactional",
            Polypoly_Parent_Category: ["pppc:FinancialData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen über einen Einkauf, Ausgaben oder Einkommen",
            Explanation_EN:
                "Information about an purchasing, spending or income",
        },
        {
            "dpv:Category": "dpv:Username",
            count: 15,
            "dpv:Superclass": "dpv:Identifying",
            Translation_DE: "Benutzername",
            Translation_EN: "Username",
            Polypoly_Parent_Category: [
                "pppc:IndividualData",
                "pppc:TechnicalData",
            ],
            Synonyms: "",
            Explanation_DE: "Informationen über Benutzernamen.",
            Explanation_EN: "Information about usernames.",
        },
        {
            "dpv:Category": "dpv:VoiceCommunicationRecording",
            count: 35,
            "dpv:Superclass": "dpv:Communication",
            Translation_DE: "Aufzeichnung der Sprachkommunikation",
            Translation_EN: "Voice Communication Recording",
            Polypoly_Parent_Category: ["pppc:SocialData"],
            Synonyms: "",
            Explanation_DE:
                "Informationen über sprachlich aufgezeichnete Kommunikation (z. B. Telefonie, VoIP)",
            Explanation_EN:
                "Information about vocal recorded communication (e.g. telephony, VoIP)",
        },
        {
            "dpv:Category": "unspecified",
            count: 40,
            "dpv:Superclass": "",
            Translation_DE: "unspezifiziert",
            Translation_EN: "unspecified",
            Polypoly_Parent_Category: [""],
            Synonyms: "",
            Explanation_DE: "unspezifizierte Zwecke",
            Explanation_EN: "purpose unspecified",
        },
    ],
    description: {
        value: {
            en: "Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Five companies in the U.S. information technology industry, along with Amazon, Google, Microsoft, and Facebook.[8][9][10] Its hardware products include the iPhone smartphone, the iPad tablet computer, the Mac personal computer, the iPod portable media player, the Apple Watch smartwatch, the Apple TV digital media player, the AirPods wireless earbuds, the AirPods Max headphones, and the HomePod smart speaker line. Apple's software includes iOS, iPadOS, macOS, watchOS, and tvOS operating systems, the iTunes media player, the Safari web browser, the Shazam music identifier, and the iLife and iWork creativity and productivity suites, as well as professional applications like Final Cut Pro X, Logic Pro, and Xcode. Its online services include the iTunes Store, the iOS App Store, Mac App Store, Apple Arcade, Apple Music, Apple TV+, Apple Fitness+, iMessage, and iCloud. Other services include Apple Store, Genius Bar, AppleCare, Apple Pay, Apple Pay Cash, and Apple Card.\nApple was founded by Steve Jobs, Steve Wozniak, and Ronald Wayne in April 1976 to develop and sell Wozniak's Apple I personal computer, though Wayne sold his share back to Jobs and Wozniak within 12 days. It was incorporated as Apple Computer, Inc., in January 1977, and sales of its computers, including the Apple II, grew quickly.",
            de: "Apple Inc. [ˈæpəlˌɪŋk] ist ein US-amerikanischer Hard- und Softwareentwickler und ein Technologieunternehmen, das Computer, Smartphones und Unterhaltungselektronik sowie Betriebssysteme und Anwendungssoftware entwickelt und vertreibt. Zudem betreibt Apple ein Internet-Vertriebsportal für Musik, Filme und Software. Der Hauptsitz von Apple, der Apple Park, befindet sich im kalifornischen Cupertino.\nApple wurde 1976 von Steve Wozniak, Steve Jobs und Ron Wayne als Garagenfirma gegründet und zählte zu den ersten Herstellern von Personal Computern.",
        },
        source: "Wikipedia, polyPedia",
    },
    industryCategory: {
        id: "ic:RetailAndConsumption",
        name: {
            en: "Retail & Consumption",
            de: "Handel & Konsum",
        },
    },
    jurisdictionsShared: {
        children: ["EU-GDPR", "Five-Eyes"],
    },
};
