export default {
    totalEvents: "totalEvents",
    picturesCount: "picturesCount",
    locationsData: "locationsData",
    randomAdInterests: "randomAdInterests",
    numberInterests: "numberInterests",
    displayData: "displayData",
    reactionsTypeCountPairs: "reactionsTypeCountPairs",
    messagesThreadsData: "messagesThreadsData",
    messagesCount: "messagesCount",
    offFacebookEventTypes: "offFacebookEventTypes",
    onOffEvents: "onOffEvents",
    companiesCount: "companiesCount",
    companiesWithAdsCount: "companiesWithAdsCount",
    commonAdvertisersData: "commonAdvertisersData",
    connectedAdvertisersCount: "connectedAdvertisersCount",
    connectedAdvertiserNames: "connectedAdvertiserNames",
    postReactionsTypes: "postReactionsTypes",
    eventsTypeCountPairs: "eventsTypeCountPairs",
    missingKnownFileNames: "missingKnownFileNames",
    missingCommonFileNames: "missingCommonFileNames",
    unknownFolderNames: "unknownFolderNames",
    importersData: "importersData",
    bubblesData: "bubblesData",
    sortedAdInterests: "sortedAdInterests",
};
