[package]
name = "feature_categories"
version = "0.1.0"
edition = "2021"

[dependencies]
core_failure = { path = "../core_failure" }
io = { path = "../io" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
pretty_assertions = "1.2.1"
