name: polyPod Android integration test
on:
    push:
        paths:
            - "feature-utils/**"
            - "features/**"
            - "platform/feature-api/**"
            - "platform/core/**"
            - "platform/android/**"
            - ".github/workflows/android-test.yml"

jobs:
    test:
        name: Test Android app
        runs-on: macOS-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "npm"
                  cache-dependency-path: "**/package-lock.json"
            - name: Build prerequisites
              run: ./build.js
              env:
                POLYPOD_BUILD_PLATFORMS: android
            - uses: actions/setup-java@v3
              with:
                  distribution: 'zulu'
                  java-version: 11
                  cache: 'gradle'
            - name: Test Android
              uses: ReactiveCircus/android-emulator-runner@76c2bf6f95ed6458fd659a1bdb680a0f8df232dc
              with:
                working-directory: platform/android
                arch: 'x86_64'
                api-level: 30
                script: ./gradlew connectedAndroidTest
