name: Testing polyPod in iOS
on: [push, pull_request]

jobs:
  test:
    name: Testing polyPod app
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build iOS
        run: |
          cd ios/PolyPodApp
          xcodebuild -workspace PolyPod.xcodeproj/project.xcworkspace/ \
                     -scheme polyPod
                     -destination platform=iOS\ Simulator,OS=13.3,name=iPhone\ 11 \
                     clean test | xcpretty
