name: Testing polyPod in iOS
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        simDestination: [13.3,14.4]
    name: Testing polyPod iOS app for destination ${{matrix.simDestination}}
    runs-on: macOS-11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build iOS
        with:
          env:
            simDestination: ${{matrix.simDestination}}
        run: |
          cd ios
          set -o pipefail
          make test | xcpretty
