name: Testing polyPod in iOS
on: [push, pull_request]

jobs:
  test:
    name: Testing polyPod app
    runs-on: macOS-10.15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build iOS
        run: |
          cd ios
          set -o pipefail
          make test | xcpretty
