name: Upload APK to Google Play
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      POLYPOD_POLYPEDIA_REPORT_URL:
        required: true
      POLYPOD_POLYPEDIA_REPORT_AUTHORIZATION:
        required: true
      POLYPOD_ANDROID_UPLOAD_KEYSTORE_FILE:
        required: true
      POLYPOD_ANDROID_UPLOAD_KEYSTORE_PASS:
        required: true
      POLYPOD_ANDROID_UPLOAD_KEY_ALIAS:
        required: true
      POLYPOD_ANDROID_STORE_SERVICE_ACCOUNT_JSON:
        required: true
jobs:
  check_branch:
    name: "Check branch ('release*' or 'main' or 'prod4pod-1426')."
    runs-on: ubuntu-latest
    steps:
      - id: early_exit
        if: ${{ github.ref != 'refs/heads/main' && startsWith(github.ref, 'refs/heads/release') != true && startsWith(github.ref, 'refs/heads/prod4pod-1426') != true }}
        name: Early exit failure if not main or release branch.
        run: exit 1
  build_test_upload:
    name: Build, test, and upload to Google Play.
    needs: check_branch
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building and Uploading APK from ${{ github.ref }}."
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.8
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build API and features
        run: ./build.js
        env:
            POLYPOD_POLYPEDIA_REPORT_URL: ${{ secrets.POLYPOD_POLYPEDIA_REPORT_URL }}
            POLYPOD_POLYPEDIA_REPORT_AUTHORIZATION: ${{ secrets.POLYPOD_POLYPEDIA_REPORT_AUTHORIZATION }}
      - name: Lint API and features
        run: ./build.js lint
      - name: Test API and features
        run: xvfb-run --auto-servernum ./build.js test
      - name: Test android
        working-directory: platform/android
        run: ./gradlew test
      - name: Write POLYPOD_ANDROID_UPLOAD_KEYSTORE_FILE
        working-directory: platform/android/app
        run: 'echo -n "$KEYSTORE" | base64 --decode > keystore.tmp'
        env:
          KEYSTORE: ${{ secrets.POLYPOD_ANDROID_UPLOAD_KEYSTORE_FILE }}
      - name: Build android
        working-directory: platform/android
        run: ./gradlew assemble -Psign=true
        env:
          POLYPOD_ANDROID_UPLOAD_KEYSTORE_FILE: keystore.tmp
          POLYPOD_ANDROID_UPLOAD_KEYSTORE_PASS: ${{ secrets.POLYPOD_ANDROID_UPLOAD_KEYSTORE_PASS }}
          POLYPOD_ANDROID_UPLOAD_KEY_ALIAS: ${{ secrets.POLYPOD_ANDROID_UPLOAD_KEY_ALIAS }}
      - name: Set VERSION_CODE environment variable.
        run: echo "VERSION_CODE=$( ./getPackageInfo.sh /usr/local/lib/android/sdk/build-tools/30.0.0/aapt ./app/build/outputs/apk/release/app-release.apk versionCode )" >> $GITHUB_ENV
        working-directory: platform/android
      - name: Set VERSION_NAME environment variable.
        run: echo "VERSION_NAME=$( ./getPackageInfo.sh /usr/local/lib/android/sdk/build-tools/30.0.0/aapt ./app/build/outputs/apk/release/app-release.apk versionName )" >> $GITHUB_ENV
        working-directory: platform/android
      - name: Declare some variables to help label APK Upload
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "##[set-output name=sha_short;]$(echo ${GITHUB_SHA::7})"
