name: Upload IPA to App Store
on: workflow_dispatch
jobs:
  check_branch:
    name: "Check branch ('release*' or 'main')."
    runs-on: macos-latest
    steps:
      - id: early_exit
        if: ${{ github.ref != 'refs/heads/main' && startsWith(github.ref, 'refs/heads/release') != true }}
        name: Early exit failure if not main or release branch.
        run: exit 1
  build_test_upload:
    name: Build, test, and upload to App Store
    needs: check_branch
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: 16
            cache: "npm"
            cache-dependency-path: "**/package-lock.json"
      - name: Build core and features
        run: ./build.js
        env:
            POLYPOD_POLYPEDIA_REPORT_URL: ${{ secrets.POLYPOD_POLYPEDIA_REPORT_URL }}
            POLYPOD_POLYPEDIA_REPORT_AUTHORIZATION: ${{ secrets.POLYPOD_POLYPEDIA_REPORT_AUTHORIZATION }}
      - name: Lint core and features
        run: ./build.js lint
      - name: Test core and features
        run: xvfb-run --auto-servernum ./build.js test
      - name: Lock xcode version
        run: sudo xcode-select -switch /Applications/Xcode_12.4.app
      - name: Run tests
        working-directory: ios
        run: |
          set -o pipefail
          make test | xcpretty
      - name: Install distribution prerequisites
        working-directory: ios
        run: make install_distribution_prerequisites
        env:
          POLYPOD_APPLE_IOS_DISTRIBUTION_CERTIFICATE: ${{ secrets.POLYPOD_APPLE_IOS_DISTRIBUTION_CERTIFICATE }}
          POLYPOD_APPLE_IOS_DISTRIBUTION_CERTIFICATE_PWD: ${{ secrets.POLYPOD_APPLE_IOS_DISTRIBUTION_CERTIFICATE_PWD }}
          POLYPOD_APPLE_IOS_DISTRIBUTION_PROVISIONING_PROFILE: ${{ secrets.POLYPOD_APPLE_IOS_DISTRIBUTION_PROVISIONING_PROFILE }}
          POLYPOD_APPLE_APP_STORE_CONNECT_API_KEY: ${{ secrets.POLYPOD_APPLE_APP_STORE_CONNECT_API_KEY }}
          POLYPOD_APPLE_IOS_APPSTORE_API_KEY_ID: ${{ secrets.POLYPOD_APPLE_IOS_APPSTORE_API_KEY_ID }}
      - name: Archive application
        working-directory: ios
        run: |
          set -o pipefail
          make archive | xcpretty
      - name: Export IPA
        working-directory: ios
        run: |
          set -o pipefail
          make export_ipa | xcpretty
      - name: Upload IPA
        working-directory: ios
        run: |
          set -o pipefail
          make upload_ipa | xcpretty
        env:
          POLYPOD_APPLE_IOS_APPSTORE_API_ISSUER_ID: ${{ secrets.POLYPOD_APPLE_IOS_APPSTORE_API_ISSUER_ID }}
          POLYPOD_APPLE_IOS_APPSTORE_API_KEY_ID: ${{ secrets.POLYPOD_APPLE_IOS_APPSTORE_API_KEY_ID }}
