name: Upload APK to Google Play
on:
  workflow_dispatch:
  workflow_call:
jobs:
  check_branch:
    name: "Check branch ('release*' or 'main')."
    runs-on: ubuntu-latest
    steps:
      - id: early_exit
        if: ${{ github.ref != 'refs/heads/main' && startsWith(github.ref, 'refs/heads/release') != true }}
        name: Early exit failure if not main or release branch.
        run: exit 1
  build_test_upload:
    name: Build, test, and upload to Google Play.
    needs: check_branch
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building and Uploading APK from ${{ github.ref }}."
