name: Upload IPA to App Store
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      POLYPOD_POLYPEDIA_REPORT_URL:
        required: true
      POLYPOD_POLYPEDIA_REPORT_AUTHORIZATION:
        required: true
      POLYPOD_APPLE_IOS_APPSTORE_P12_FILE_BASE64:
        required: true
      POLYPOD_APPLE_IOS_APPSTORE_P12_PASS:
        required: true
      POLYPOD_APPLE_IOS_APPSTORE_PROVISION_PROFILE_BASE64:
        required: true
      POLYPOD_APPLE_IOS_APPSTORE_API_PRIVATE_KEY_BASE64:
        required: true
      POLYPOD_APPLE_IOS_APPSTORE_API_KEY_ID:
        required: true
      POLYPOD_APPLE_IOS_APPSTORE_API_ISSUER_ID:
        required: true
jobs:
  build_test_upload:
    name: Build, test, and upload to App Store
    runs-on: macos-11
    if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release') == true }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: 16
            cache: "npm"
            cache-dependency-path: "**/package-lock.json"
      - name: Build core and features
        run: ./build.js
        env:
            POLYPOD_POLYPEDIA_REPORT_URL: ${{ secrets.POLYPOD_POLYPEDIA_REPORT_URL }}
            POLYPOD_POLYPEDIA_REPORT_AUTHORIZATION: ${{ secrets.POLYPOD_POLYPEDIA_REPORT_AUTHORIZATION }}
      - name: Lock xcode version
        working-directory: platform/ios
        run: make lockxcodeversion
      - name: Run tests
        working-directory: platform/ios
        run: |
          set -o pipefail
          make test | xcpretty
      - name: Install distribution prerequisites
        working-directory: platform/ios
        run: make install_distribution_prerequisites
        env:
          POLYPOD_APPLE_IOS_APPSTORE_P12_FILE_BASE64: ${{ secrets.POLYPOD_APPLE_IOS_APPSTORE_P12_FILE_BASE64 }}
          POLYPOD_APPLE_IOS_APPSTORE_P12_PASS: ${{ secrets.POLYPOD_APPLE_IOS_APPSTORE_P12_PASS }}
          POLYPOD_APPLE_IOS_APPSTORE_PROVISION_PROFILE_BASE64: ${{ secrets.POLYPOD_APPLE_IOS_APPSTORE_PROVISION_PROFILE_BASE64 }}
          POLYPOD_APPLE_IOS_APPSTORE_API_PRIVATE_KEY_BASE64: ${{ secrets.POLYPOD_APPLE_IOS_APPSTORE_API_PRIVATE_KEY_BASE64 }}
          POLYPOD_APPLE_IOS_APPSTORE_API_KEY_ID: ${{ secrets.POLYPOD_APPLE_IOS_APPSTORE_API_KEY_ID }}
      - name: Export and upload IPA
        working-directory: platform/ios
        run: |
          set -o pipefail
          make upload_ipa | xcpretty
        env:
          POLYPOD_APPLE_IOS_APPSTORE_API_ISSUER_ID: ${{ secrets.POLYPOD_APPLE_IOS_APPSTORE_API_ISSUER_ID }}
          POLYPOD_APPLE_IOS_APPSTORE_API_KEY_ID: ${{ secrets.POLYPOD_APPLE_IOS_APPSTORE_API_KEY_ID }}
