name: Upload IPA to App Store
on: [workflow_dispatch, workflow_call]
jobs:
  build_test_upload:
    name: Build, test, and upload to App Store
    runs-on: macos-11
    if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release') == true }}
    steps:
      - run: echo "Building and Uploading APK from ${{ github.ref }}."
